'use strict';
const icons = {
 compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2.5 5.5L8 16l2.5-5.5L16 8Z"/>',
 home:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 search:'<circle cx="10.8" cy="10.8" r="7.3"/><path d="m16 16 5 5"/>',
 ship:'<path d="m3 13 9-3 9 3-3 6H6l-3-6Zm4-1V6h10v6M10 6V3h4v3M3 21c3-3 6 3 9 0s6 3 9 0"/>',
 leaf:'<path d="M20 3c-8 0-15 3-15 10a6 6 0 0 0 6 6c7 0 9-8 9-16Z M3 22 15 10"/>',
 file:'<path d="M14 3H5v18h14V8l-5-5Zm0 0v5h5M8 12h8M8 16h6"/>',
 chat:'<path d="M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4Z"/><path d="M8 10h8M8 14h5"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 chevron:'<path d="m9 5 7 7-7 7"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',
 external:'<path d="M14 3h7v7M21 3l-10 10M10 3H3v18h18v-7"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7v1"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',
 wave:'<path d="M2 8c4-5 6 5 10 0s6 5 10 0M2 16c4-5 6 5 10 0s6 5 10 0"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
 settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',
 alert:'<path d="m12 3 10 18H2L12 3Zm0 6v5m0 3v1"/>',
 wind:'<path d="M3 8h12a3 3 0 1 0-3-3M3 12h16a3 3 0 1 1-3 3M3 16h5a3 3 0 1 1-3 3"/>',
 book:'<path d="M12 5C8 2 4 3 2 4v16c3-2 7-2 10 0 3-2 7-2 10 0V4c-2-1-6-2-10 1Zm0 0v15"/>',
 plus:'<path d="M12 5v14M5 12h14"/>'
};
const ico=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.file}</svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeRead=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k))??fallback}catch{return fallback}};
const navs=[['home','home','대시보드'],['briefing','compass','현재 운항 브리핑'],['navigation','ship','항해·시각 확인'],['regulation','search','규정 검색'],['carbon','leaf','CII · 배출량'],['report','file','보고서 작성'],['ask','chat','자유 질문'],['device','settings','사용 환경']];
const DOCS={
 sulfur:{id:'sulfur',title:'IMO 2020 · 연료 황 함유량',category:'IMO 공식 안내',ref:'MARPOL Annex VI · Regulation 14',version:'공식 웹 안내 · 2026.09.17 확인',location:'서두 / What must ships do to comply?',url:'https://www.imo.org/en/mediacentre/hottopics/pages/sulphur-2020.aspx',body:['지정 배출규제해역 밖에서 사용하는 선박 연료유의 황 함유량 한도는 0.50% m/m, 지정 SOx 배출규제해역에서는 0.10% m/m이다.','기국이 승인한 동등한 배출 저감 수단이 적용될 수 있다. 항해 위치와 항만별 요구사항을 별도로 확인해야 한다.'],note:'공식 안내를 한국어로 요약했습니다. 법령 원문 인용이나 선박별 적합 판정이 아닙니다.'},
 cii:{id:'cii',title:'IMO · CII 평가와 개선 계획',category:'IMO 공식 안내',ref:'MARPOL Annex VI · Regulation 28',version:'공식 웹 안내 · 2026.09.17 확인',location:'How do the ratings work? / Which ships…',url:'https://www.imo.org/en/mediacentre/hottopics/pages/eexi-cii-faq.aspx',body:['CII는 연간 운항 탄소집약도를 평가하며, 관련 대상 선박은 일반적으로 5,000 GT 이상이다. 실제 연간 CII와 요구 CII를 비교하고 검증하여 A–E 등급을 결정한다.','D 등급이 3년 연속이거나 E 등급이 1년인 선박은 C 이상 달성을 위한 시정조치 계획을 제출해야 한다.'],note:'공식 FAQ의 한국어 요약입니다. 이 데모의 단순 계산값으로 공식 CII 등급을 판정하지 않습니다.'},
 checklist:{id:'checklist',title:'HAE-01 · 연료 전환 점검표',category:'선내 문서 · 샘플',ref:'DEMO-FUEL-01 · §2–3',version:'가상 문서 v1.0 · 2026.09.17',location:'샘플 1쪽 · 전환 전 확인',body:['전환 전 항로의 적용 해역, 사용 연료의 공급서류, 승인된 선내 절차를 확인한다.','담당 기관사는 전환 전후 시각, 위치, 사용 탱크를 기록하고 검토자에게 점검표를 인계한다.'],note:'흐름 검증을 위해 작성한 가상 점검표입니다. 실제 장비 조작 절차가 아닙니다.'},
 noon:{id:'noon',title:'HAE-01 · Noon Report',category:'운항 데이터 · 샘플',ref:'DEMO-NOON-0917',version:'가상 항해 V.026 · 2026.09.17 12:00 KST',location:'일일 운항 기록 · 1쪽',body:['선박 HAE-01, 부산 → 싱가포르. 직전 24시간 항해 거리 312 nm, 평균 속력 13.0 kn, 연료 사용량 24.8 t.','기준 시각 2026년 9월 17일 12:00 KST. 출항 후 경과 48시간, 잔여 항해 시간 72시간, 도착 예정 9월 20일 12:00 KST.','수치는 모두 가상 데이터이다. 통신 연결 전 샘플이며 현재 해상 상태를 나타내지 않는다.'],note:'실제 선박·AIS·기상 데이터와 연결되지 않은 샘플 기록입니다.'},
 carbon:{id:'carbon',title:'HAE-01 · 연간 배출량 계산 입력',category:'계산 데이터 · 샘플',ref:'DEMO-CARBON-2026',version:'가상 연간 데이터 · 사용자 입력값 사용',location:'계산 가정 · 1쪽',body:['연료 사용량 기본값 5,400 t, 환산계수 가정 3.114 tCO₂/t fuel, 재화중량 50,000 DWT, 연간 항해 거리 60,000 nm.','배출량 = 연료 사용량 × 환산계수. 단순 집약도 = CO₂(t) × 1,000,000 ÷ [DWT(t) × 거리(nm)].','선종별 계수, 보정 인자, 제외 항차, 공식 등급 경계는 반영하지 않는다. 공식 CII 등급은 산정하지 않는다.'],note:'모든 입력과 계수는 데모 가정입니다. 연간 합산 데이터 흐름과 재계산 동작을 확인하기 위한 화면입니다.'}
};
const ENGLISH={
 sulfur:{query:'What is the fuel sulphur limit in a SOx ECA?',title:'Check the limit for the applicable area.',tag:'Fuel · Air emissions',metrics:[['Outside SOx ECAs','0.50','% m/m'],['Designated SOx ECA','0.10','% m/m'],['Ship applicability','Unconfirmed','Route · fuel · approved equipment']],summary:'The limit is 0.50% outside designated SOx ECAs and 0.10% inside them. Check the route, fuel documents and any approved equivalent arrangement before assessing HAE-01.',checks:['Confirm applicable areas and port requirements','Check fuel documentation','Review the approved onboard procedure']},
 cii:{query:'What corrective action is required for a D or E CII rating?',title:'Check the rating and the number of consecutive years.',tag:'Environment · CII',metrics:[['D rating','3','consecutive years'],['E rating','1','year'],['Plan target','C or above','Corrective action plan']],summary:'A D rating for three consecutive years or E for one year requires a corrective action plan targeting C or above. HAE-01 has no verified annual rating history in this demo, so its status cannot be determined.',checks:['Obtain verified annual ratings','Review SEEMP and the improvement plan','Consult the responsible reviewer']},
 checklist:{query:'What should a fuel changeover checklist record?',title:'Record the changeover and supporting documents.',tag:'Onboard procedure · Sample',metrics:[['Record fields','3','Time · position · tank'],['Sources','2','Checklist · IMO guidance'],['Document status','Sample','Not an operating procedure']],summary:'This fictional checklist records time, position and tank before and after changeover for review. Actual operations require the vessel’s approved procedure.',checks:['Review fuel documents','Complete the changeover record','Request engineering review']}
};
const RULES={
 sulfur:{query:'배출규제해역에서 연료 황 함유량 기준은?',title:'해역에 따라 연료의 황 함유량 기준이 달라집니다.',tag:'연료 · 대기오염',metrics:[['일반 해역','0.50','% m/m'],['지정 SOx ECA','0.10','% m/m'],['선박별 적용','추가 확인','항로 · 연료 · 승인 설비']],summary:'일반 해역과 지정 SOx 배출규제해역의 기준을 구분해 확인하세요. HAE-01의 실제 적용 여부는 항로·연료 서류·승인된 동등 수단을 확인한 뒤 판단해야 합니다.',checks:['항로의 적용 해역과 항만 요구사항 확인','연료 공급서류와 황 함유량 대조','선내 절차에 따른 전환 기록 검토'],docs:['sulfur','checklist']},
 cii:{query:'CII D 또는 E 등급이면 어떤 조치가 필요한가요?',title:'등급과 연속 기간을 함께 확인해야 합니다.',tag:'환경 · CII',metrics:[['D 등급','3','년 연속'],['E 등급','1','년'],['계획 목표','C 이상','시정조치 계획']],summary:'IMO 안내는 D 등급 3년 연속 또는 E 등급 1년인 경우 C 이상 달성을 위한 시정조치 계획을 요구합니다. 샘플 선박의 검증된 연간 등급 이력은 아직 없어 해당 여부를 확정할 수 없습니다.',checks:['검증된 연간 CII 등급 이력 확인','SEEMP와 개선 계획 검토','선박별 검증 담당자에게 확인'],docs:['cii','carbon']},
 checklist:{query:'연료 전환 점검표에는 무엇을 기록하나요?',title:'전환 기록과 확인 서류를 함께 남깁니다.',tag:'선내 절차 · 샘플',metrics:[['기록 항목','3','시각 · 위치 · 탱크'],['연결 문서','2','점검표 · IMO 안내'],['문서 상태','샘플','실제 선내 절차 아님']],summary:'가상 점검표에는 전환 전후 시각·위치·사용 탱크를 기록하고 관련 서류와 함께 검토자에게 인계하는 흐름을 담았습니다. 실제 작업은 해당 선박의 승인 절차가 필요합니다.',checks:['관련 연료 서류 확인','전환 전후 기록 작성','기관 담당자의 검토 요청'],docs:['checklist','sulfur']}
};
const state={language:'ko',offline:false,engine:'backend',page:'home',menu:false,result:null,query:'',filter:'all',loading:false,error:null,sim:'normal',requestId:0,reviewed:new Set(),history:safeRead('haedap-history',[]),report:safeRead('haedap-report',{title:'HAE-01 운항 검토 보고서',type:'규정 검토',text:'',sources:[]}),carbon:{fuel:5400,factor:3.114,dwt:50000,distance:60000},carbonError:'',calc:null,saved:false};
if(!Array.isArray(state.history))state.history=[];
if(!state.report||typeof state.report.text!=='string'||!Array.isArray(state.report.sources))state.report={title:'HAE-01 운항 검토 보고서',type:'규정 검토',text:'',sources:[]};
state.report.sources=state.report.sources.filter(x=>DOCS[x]);
function writeLocal(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{toast('이 브라우저에서는 저장할 수 없습니다. 파일로 내려받아 주세요.');return false}}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500)}
const btn=(label,action,cls='secondary',extra='')=>`<button class="btn ${cls}" data-action="${action}" ${extra}>${label}</button>`;
const chip=(text,cls='')=>`<span class="badge ${cls}">${text}</span>`;
function connectionNotice(){if(state.engine==='backend')return backendNotice();return `<div class="mode-notice"><span>${ico('info')} ${state.offline?'외부망 차단 상황 · 모의':'샘플 시나리오 모드'} · ${state.engine==='api'?'API 방식 체험':'선내 실행 방식 체험'}</span><button class="text-btn" data-action="demo-settings">실행 환경 설정</button></div>`}
function getRule(){const r=RULES[state.result];if(!r)return null;return state.language==='en'?{...r,...ENGLISH[state.result]}:r}
function shell(){return `<aside class="sidebar ${state.menu?'is-open':''}" aria-label="주 메뉴"><a class="brand" href="#home"><span class="brand-symbol">${ico('compass')}</span><span>해,답<small>YOUR MARITIME COPILOT</small></span></a><div class="workspace-label">WORKSPACE</div><nav>${navs.map(([id,icon,label])=>`<a href="#${id}" class="nav-link ${state.page===id?'active':''}" ${state.page===id?'aria-current="page"':''}>${ico(icon)}<span>${label}</span>${id==='report'&&state.report.sources.length?`<span class="nav-count">${state.report.sources.length}</span>`:''}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="ship-card"><span class="ship-avatar">${ico('ship')}</span><div><strong>HAE-01</strong><small>벌크선 · 50,000 DWT</small></div><span class="live-dot"></span></div><button class="demo-settings" data-action="demo-settings">${ico('settings')} 데모 상태 설정 ${ico('chevron')}</button><div class="private-note">${ico('lock')} 선원 업무 워크스페이스</div></div></aside>${state.menu?'<button class="nav-backdrop" data-action="close-menu" aria-label="메뉴 닫기"></button>':''}<div class="shell"><header class="topbar"><div class="breadcrumbs"><button class="icon-btn mobile-menu" data-action="menu" aria-label="메뉴 열기">${ico('menu')}</button><span>워크스페이스</span><span class="slash">/</span><strong>${navs.find(x=>x[0]===state.page)?.[2]||'대시보드'}</strong></div><div class="top-right"><span class="badge sample"><span class="live-dot"></span> 샘플 데이터</span><span class="avatar" title="데모 사용자">해</span></div></header><main id="main" tabindex="-1">${connectionNotice()}${content()}</main><footer>해,답 · 선원 업무 지원 <span>가상 운항 데이터 · 문서 검색 · 계산 도구 · 실제 운항 판단용이 아닙니다.</span></footer></div>`}
function pagehead(eyebrow,title,subtitle,action=''){return `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`}
function routeSvg(){return `<svg class="route-art" viewBox="0 0 520 225" role="img" aria-label="부산에서 싱가포르로 이동하는 샘플 항로 개념도"><defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0H0V28" fill="none" stroke="#ffffff" stroke-opacity=".05"/></pattern><linearGradient id="routeFade"><stop stop-color="#55cdb3"/><stop offset="1" stop-color="#c2f6e9"/></linearGradient></defs><rect width="520" height="225" fill="url(#grid)"/><path d="M50 0 105 25 142 27 176 65 162 92 195 115 198 145 221 150 232 198 214 225H0V0M321 0l-2 40 22 28-13 25 15 18 19-9-4-33 20-23L368 0M278 134l13 11 6 30-15 9-7-27M421 74l-7 28 26 37-10 41 28 26 4-43-11-32 1-29" fill="#294651" stroke="#46606a" stroke-width="1"/><path d="M333 46C352 92 289 116 277 153S253 176 244 198" fill="none" stroke="#94c9bf" stroke-width="2" stroke-dasharray="5 6"/><path d="M333 46C352 92 301 109 286 132" fill="none" stroke="url(#routeFade)" stroke-width="3"/><circle cx="333" cy="46" r="5" fill="#e5fff7"/><circle cx="244" cy="198" r="5" fill="#162e3b" stroke="#8dc5b9" stroke-width="2"/><circle cx="286" cy="132" r="20" fill="#63d9ba" opacity=".1"/><circle cx="286" cy="132" r="12" fill="#63d9ba" opacity=".18"/><path d="m283 123 7 9-9 7 2-16Z" fill="#8fe8d0"/><text x="346" y="40" fill="#f5fffc" font-size="12">부산</text><text x="256" y="209" fill="#cadcd9" font-size="12">싱가포르</text><text x="310" y="145" fill="#9ce8d3" font-size="11">HAE-01</text><text x="419" y="25" fill="#b1c6ca" font-size="10">N ↑</text><text x="48" y="155" fill="#819ca5" font-size="11" letter-spacing="3">SOUTH CHINA SEA</text></svg>`}
function voyageCard(){return `<section class="voyage-card"><div class="voyage-map"><div class="map-top"><span>${ico('compass')} 현재 운항 브리핑</span><span class="map-tag">항해 중 · 샘플</span></div>${routeSvg()}<div class="map-bottom"><span>BUSAN <span class="route-dash">―</span> SINGAPORE</span><button class="map-detail-link" data-nav="navigation">좌표 지도 열기 ↗</button></div></div><div class="voyage-info"><div class="section-line"><span class="eyebrow">VOYAGE 026</span><span class="muted small">09.17 · 12:00 KST 기준</span></div><div class="voyage-title"><h2>안정적인 항해, <br>다음 업무를 준비할 시간.</h2><span class="weather-symbol">${ico('wave')}</span></div><div class="voyage-metrics"><div><small>평균 속력</small><strong>13.0 <span>kn</span></strong></div><div><small>24시간 연료 사용</small><strong>24.8 <span>t</span></strong></div><div><small>도착 예정</small><strong>09.20 <span>12:00</span></strong></div></div><div class="voyage-progress"><span></span></div><div class="section-line"><small class="muted">항해 시간 40% 경과 · 잔여 72시간</small><button class="text-btn" data-nav="briefing">브리핑 보기 ${ico('arrow')}</button></div></div></section>`}
function home(){return `${pagehead('ON BOARD, IN CONTROL','오늘의 운항, 한눈에.','필요한 정보를 찾고, 근거를 확인하고, 다음 업무로 이어가세요.',`<span class="date-label">${ico('clock')} 2026년 9월 17일 · 샘플 기준일</span>`)}${voyageCard()}<section class="work-section"><div class="section-heading"><h2>어떤 업무를 도와드릴까요?</h2><span class="muted small">답변부터 근거까지, 한곳에서</span></div><div class="task-grid"><button class="task-card featured" data-nav="regulation"><div class="task-top"><span class="task-icon">${ico('search')}</span><span class="tiny-label">추천 시작점</span></div><h3>규정 검색</h3><p>필요한 규정을 찾고<br>조항과 출처를 확인하세요.</p><span class="task-bottom">규정 검색 시작 ${ico('arrow')}</span><span class="card-watermark">§</span></button><button class="task-card" data-nav="carbon"><span class="task-icon green">${ico('leaf')}</span><h3>CII · 배출량 확인</h3><p>운항 수치로 배출량과<br>탄소집약도를 살펴보세요.</p><span class="task-bottom">계산 흐름 체험 ${ico('arrow')}</span></button><button class="task-card" data-nav="report"><span class="task-icon blue">${ico('file')}</span><h3>보고서 작성</h3><p>확인한 근거를 모아<br>보고서 초안을 작성하세요.</p><span class="task-bottom">초안 작성하기 ${ico('arrow')}</span></button><button class="task-card" data-nav="ask"><span class="task-icon sand">${ico('chat')}</span><h3>자유 질문</h3><p>어디서 시작할지 모를 때,<br>편하게 질문해 보세요.</p><span class="task-bottom">질문하기 ${ico('arrow')}</span></button></div></section><section class="scenario-section"><div class="section-heading"><div><h2>질문 하나로, 흐름을 체험해 보세요.</h2><p class="muted small">준비된 시나리오는 실제 데이터 연결 없이 바로 실행됩니다.</p></div><span class="scenario-mark">TRY A SCENARIO</span></div><div class="scenario-list">${scenarioButton('sulfur','01','배출규제해역, 연료 기준은?','규정 검색 → 근거 확인 → 보고서')}${scenarioButton('cii','02','CII 등급이 낮으면 어떻게 하죠?','평가 기준 → 필요한 조치 확인')}${scenarioButton('briefing','03','오늘 운항을 한 번에 정리해 줘','운항 수치 → 요약 → 보고서')}${scenarioButton('integrated','04','우리 선박 배출량과 CII 규정을 함께 알려줘','입력값 → 계산 → 적용 조건 → 보고서')}</div></section>`}
function scenarioButton(id,num,title,sub){return `<button class="scenario-item" data-scenario="${id}"><span class="scenario-number">${num}</span><span><strong>${title}</strong><small>${sub}</small></span>${ico('arrow')}</button>`}
function steps(){return `<div class="flow-steps"><span class="done"><i>1</i> 질문하기</span><b>—</b><span class="${state.result?'done':''}"><i>2</i> 답변 살펴보기</span><b>—</b><span class="${state.reviewed.size?'done':''}"><i>3</i> 근거 확인</span><b>—</b><span><i>4</i> 보고서 담기</span></div>`}
function searchPanel(free=false){return `<section class="panel search-panel"><form id="search-form" novalidate><label for="query">${free?'궁금한 업무를 질문해 주세요.':'어떤 규정이 궁금하신가요?'}</label><div class="search-input-wrap">${ico(free?'chat':'search')}<input id="query" name="query" maxlength="500" value="${esc(state.query)}" placeholder="${free?'예: 오늘 운항 상태를 정리해 줘':'예: 배출규제해역에서 연료 황 함유량 기준은?'}" autocomplete="off" ${state.error==='empty'?'aria-invalid="true" aria-describedby="query-error"':''}/><button class="btn primary" type="submit" ${state.loading?'disabled':''}>${state.loading?'확인 중…':free?'질문하기':'검색하기'} ${ico('arrow')}</button></div>${state.error==='empty'?'<p class="field-error" id="query-error" role="alert">질문을 입력하거나 아래 예시를 선택해 주세요.</p>':''}</form><div class="answer-language"><label for="answer-language">답변 언어</label><select id="answer-language"><option value="ko" ${state.language==='ko'?'selected':''}>한국어</option><option value="en" ${state.language==='en'?'selected':''}>English</option></select><span class="small muted">한·영 예시 질문 지원 · 원문 출처 유지</span></div><div class="suggestions"><span>예시 질문</span><button data-scenario="sulfur">${state.language==='en'?'Fuel sulphur limit':'연료 황 함유량'}</button><button data-scenario="cii">${state.language==='en'?'CII corrective action':'CII 개선 계획'}</button><button data-scenario="integrated">${state.language==='en'?'Emissions + CII rules':'배출량 + CII 규정'}</button><button data-scenario="${free?'briefing':'checklist'}">${free?'오늘 운항 요약':'연료 전환 점검표'}</button></div>${!free?`<div class="filter-row"><span class="small muted">근거 필터</span>${[['all','전체 문서'],['imo','IMO 공식 안내'],['manual','선내 문서']].map(([v,t])=>`<button data-filter="${v}" aria-pressed="${state.filter===v}" class="filter ${state.filter===v?'selected':''}">${t}</button>`).join('')}<span class="filter-count">${state.engine==='backend'?`등록 문서 ${backend.health?.documents||0}개`:'샘플 문서 5개'}</span></div>`:''}</section>`}
function regulation(free=false){return `${pagehead(free?'ASK HAEDAP':'REGULATION SEARCH',free?'어떤 업무가 궁금하신가요?':'규정을 찾고, 근거로 확인하세요.',free?'샘플 주제: 운항 브리핑, 연료 규정, CII, 보고서 작성':'핵심 기준과 확인할 내용을 정리하고, 연결된 근거까지 보여드립니다.')}${!free?steps():''}${searchPanel(free)}<div id="search-response" aria-live="polite" aria-busy="${state.loading}">${state.loading?loadingView():state.error&&state.error!=='empty'?errorView():state.result?ruleResult():emptySearch(free)}</div>`}
function loadingView(){return `<section class="panel loading"><span class="spinner"></span><h2>${state.engine==='backend'?'등록 문서에서 근거를 검색하고 있어요.':'샘플 문서에서 근거를 확인하고 있어요.'}</h2><p class="muted">${state.longWait?'30초 초과 시 표시되는 진행 안내를 재현 중입니다. 질문을 유지하고 있습니다.':'질문과 연결된 기준 · 선내 문서 확인 중'}</p><div class="skeleton"></div><div class="skeleton shorter"></div></section>`}
function emptySearch(free){return `<section class="search-empty"><span class="empty-orbit">${ico(free?'chat':'book')}</span><h2>${free?'짧은 질문으로 시작해 보세요.':'답변의 시작은, 신뢰할 수 있는 근거.'}</h2><p>위의 예시 질문을 선택하면 ${free?'준비된 업무 흐름을 체험할 수 있습니다.':'수치 · 요약 · 문서가 연결되는 흐름을 볼 수 있습니다.'}</p><div class="value-pills"><span>${ico('check')} 구분된 핵심 수치</span><span>${ico('check')} 출처가 있는 요약</span><span>${ico('check')} 확인 가능한 근거</span></div>${state.history.length?`<div class="history"><h3>최근 확인한 질문</h3>${state.history.slice(0,3).map(h=>`<button data-scenario="${esc(h.id)}">${ico('clock')}${esc(h.query)}${ico('arrow')}</button>`).join('')}</div>`:''}</section>`}
function errorView(){if(state.error==='backend')return backendErrorView();if(['offline','tool','outdated'].includes(state.error)){const messages={offline:['외부 LLM에 연결할 수 없습니다.','API 방식은 외부망 없이 새 답변을 생성할 수 없습니다. 저장 문서·계산 화면·수동 초안을 이용하거나 실행 환경을 변경하세요.'],tool:['계산 도구 실행에 실패했습니다.','입력한 질문은 유지했습니다. 계산값을 추정해 채우지 않았습니다. 다시 시도해 주세요.'],outdated:['문서의 적용 버전을 확인해야 합니다.','구버전만 검색된 상황을 재현했습니다. 적합 판정을 보류하고 승인된 개정판과 적용일을 확인해 주세요.']};const [title,desc]=messages[state.error];return `<section class="panel error-state" role="alert"><span class="error-symbol">${ico('alert')}</span><h2>${title}</h2><p>${desc}</p>${btn('다시 시도','retry','primary')}<button class="btn secondary" data-nav="carbon">저장 데이터 계산</button><button class="btn secondary" data-nav="report">수동 초안 작성</button><small>데모 상태 재현 · 실제 통신·모델 성능 시험이 아닙니다.</small></section>`}const network=state.error==='network';return `<section class="panel error-state" role="alert"><span class="error-symbol">${ico(network?'alert':'search')}</span><h2>${network?'조회 연결이 잠시 끊겼어요.':'일치하는 샘플 근거가 없습니다.'}</h2><p>${network?'입력한 질문은 유지했습니다. 다시 시도하면 샘플 응답을 불러옵니다.':'이 데모는 연료 황 함유량, CII 개선 계획, 연료 전환 점검표와 운항 요약을 지원합니다.'}</p>${network?btn('다시 시도','retry','primary'):btn('연료 규정 예시로 검색','sample-sulfur','primary')}<small>${network?'데모에서 재현한 연결 오류입니다.':'근거가 없는 질문에는 답변을 생성하지 않습니다.'}</small></section>`}
function metricsView(metrics){return `<section class="result-block"><div class="block-label"><span>01</span> 핵심 수치</div><div class="metric-grid">${metrics.map(([label,val,unit])=>`<div class="metric"><span>${esc(label)}</span><strong class="${val.length>6?'word-value':''}">${esc(val)}<small>${esc(unit)}</small></strong></div>`).join('')}</div></section>`}
function sourceCards(ids,allIds=ids){return `<section class="result-block"><div class="section-line"><div class="block-label"><span>03</span> 근거 문서</div><small class="muted">문서를 열어 출처와 연결 내용을 확인하세요.</small></div><div class="sources">${ids.map((id,i)=>{const d=DOCS[id];return `<button class="source-card" data-doc="${id}"><span class="source-icon">${ico('file')}</span><span class="source-body"><span class="source-kicker">[${allIds.indexOf(id)+1}] ${esc(d.category)}</span><strong>${esc(d.title)}</strong><small>${esc(d.ref)} · ${esc(d.location)}</small><small>${esc(d.version)} · ${d.backend&&d.category==='선내 문서'?'수집한 선내 문서':(d.url?'저장본 · 최신 개정 자동 확인 안 됨':'가상 자료')}</small></span><span class="source-end">${state.reviewed.has(id)?'<span class="reviewed">✓ 확인함</span>':'<span>근거 보기</span>'}${ico('chevron')}</span></button>`}).join('')}</div></section>`}
function ruleResult(){if(state.result==='backend')return backendResultView();if(state.result==='integrated')return integratedResult();const r=getRule();if(!r)return '';let docs=r.docs.filter(id=>state.page==='ask'||state.filter==='all'||(state.filter==='imo'?!!DOCS[id].url:!DOCS[id].url));return `<section class="result-card"><div class="result-heading"><span class="answer-icon">${ico('compass')}</span><div><div class="eyebrow">HAEDAP ANSWER <span class="answer-meta">· ${r.tag}</span></div><h2>${r.title}</h2></div>${chip('샘플 응답','soft')}</div>${metricsView(r.metrics)}<section class="result-block"><div class="block-label"><span>02</span> 요약 · 다음 확인 사항</div><p class="answer-summary">${r.summary} <button class="citation" data-doc="${r.docs[0]}" aria-label="요약의 근거 확인">[1]</button></p><div class="check-items">${r.checks.map(x=>`<span>${ico('check')}${x}</span>`).join('')}</div></section>${sourceCards(docs,r.docs)}<div class="result-footer"><span>${ico('info')} 공식 안내와 가상 선내 문서를 구분해 확인하세요.</span>${btn(`보고서에 담기 ${ico('arrow')}`,'add-rule','primary')}</div></section>`}
function briefing(){return `${pagehead('VOYAGE BRIEFING','현재 운항 브리핑','HAE-01 · V.026 · 2026.09.17 12:00 KST 기준',chip('가상 운항 기록','sample'))}${voyageCard()}<div class="ops-entry"><div><strong>날짜변경선·항만 주변 상황도 확인하세요.</strong><p>UTC와 선내 날짜, 지도 자료 상태를 함께 비교합니다.</p></div><button class="btn primary" data-nav="navigation">항해·시각 확인 ${ico('arrow')}</button></div><section class="result-card">${metricsView([['24시간 항해 거리','312','nm'],['24시간 CO₂ 추정','77.23','t · 계수 3.114 가정'],['데이터 상태','샘플','실시간 연결 전']])}<section class="result-block"><div class="block-label"><span>02</span> 운항 요약</div><p class="answer-summary">HAE-01은 부산에서 싱가포르로 항해 중인 가상 선박입니다. 최근 24시간 평균 속력은 13.0 kn, 연료 사용량은 24.8 t입니다. 다음 인계 전 연료 관련 서류와 일일 운항 기록을 함께 확인하세요. <button class="citation" data-doc="noon">[1]</button></p><div class="inline-note">${ico('info')} 날씨·항로·입항 조건은 실제 데이터 연결 전입니다. 이 화면은 운항 상태를 판정하지 않습니다.</div></section>${sourceCards(['noon'])}<div class="result-footer"><button class="text-btn" data-scenario="sulfur">관련 연료 규정 확인 ${ico('arrow')}</button>${btn(`브리핑으로 보고서 작성 ${ico('arrow')}`,'add-briefing','primary')}</div></section>`}
function calculate(){const c=state.carbon;return {emission:c.fuel*c.factor,intensity:c.fuel*c.factor*1e6/(c.dwt*c.distance)}}
function carbon(){const c=state.carbon;const v=state.calc||calculate();return `${pagehead('CARBON & EMISSIONS','숫자로 살펴보는 운항의 영향.','가상 연간 데이터를 바꾸며 배출량과 단순 탄소집약도의 변화를 확인하세요.',chip('공식 CII 등급 미산정','amber'))}<div class="carbon-layout"><section class="panel carbon-input"><div class="section-heading"><h2>연간 운항 데이터</h2><button class="text-btn" data-action="reset-carbon">기본값</button></div><p class="small muted">가상 벌크선 HAE-01 · 2026년 연간 시나리오</p><form id="carbon-form" novalidate>${[['fuel','연료 사용량','t / 년','0.1'],['factor','CO₂ 환산계수 (가정)','tCO₂ / t fuel','0.001'],['dwt','재화중량','DWT','1'],['distance','연간 항해 거리','nm','1']].map(([id,label,unit,step])=>`<label class="field" for="${id}">${label}<span class="unit-input"><input type="number" id="${id}" name="${id}" value="${esc(c[id])}" step="${step}" min="${id==='fuel'?'0':'0.001'}" inputmode="decimal" aria-describedby="carbon-validation"/><span>${unit}</span></span></label>`).join('')}<p id="carbon-validation" class="field-error" role="alert">${esc(state.carbonError)}</p><button class="btn primary full" type="submit">다시 계산하기 ${ico('arrow')}</button></form><button class="compare-btn" data-action="reduce-fuel">${ico('leaf')} 기본 연료 대비 8% 절감 시나리오</button></section><section class="result-card carbon-result"><div class="block-label"><span>01</span> 핵심 수치 <span class="badge soft">${v.version?'서버 계산 · 기록됨':'로컬 미리보기'}</span></div><div class="carbon-metrics"><div><span>연간 CO₂ 배출량</span><strong id="co2-value">${v.emission.toLocaleString('ko-KR',{maximumFractionDigits:1})}<small>tCO₂</small></strong></div><div><span>단순 탄소집약도</span><strong id="intensity-value">${v.intensity.toFixed(2)}<small>gCO₂ / (DWT·nm)</small></strong></div></div><div class="comparison"><div class="section-line"><strong>기본 샘플과 비교</strong><span>연간 CO₂ · t</span></div><div class="bar-row"><span>기본 샘플</span><div><i style="width:${Math.min(100,16815.6/Math.max(16815.6,v.emission)*100)}%"></i></div><strong>16,815.6</strong></div><div class="bar-row current"><span>현재 입력</span><div><i style="width:${Math.min(100,v.emission/Math.max(16815.6,v.emission)*100)}%"></i></div><strong>${v.emission.toLocaleString('ko-KR',{maximumFractionDigits:1})}</strong></div></div><section class="result-block"><div class="block-label"><span>02</span> 요약 · 계산 범위</div><p>현재 입력 기준, 기본 샘플 대비 배출량은 <strong>${Math.abs((v.emission/16815.6-1)*100).toFixed(1)}% ${v.emission<16815.6?'감소':v.emission>16815.6?'증가':'변화 없음'}</strong>입니다. 선종별 기준선과 보정계수를 적용하지 않아 공식 CII 등급은 계산하지 않습니다.</p><details class="formula"><summary>계산식과 가정 확인</summary><p>CO₂(t) = 연료(t) × 환산계수<br>단순 집약도 = CO₂(t) × 1,000,000 ÷ (DWT × nm)</p><p>환산계수는 가정값입니다. 선종별 계수, 제외 항차 및 보정인자는 반영하지 않았습니다.</p></details></section></section></div><section class="result-card">${sourceCards(['carbon','cii'])}<div class="result-footer"><button class="text-btn" data-scenario="cii">CII 평가 기준 보기 ${ico('arrow')}</button>${btn(`계산 결과를 보고서에 담기 ${ico('arrow')}`,'add-carbon','primary')}</div></section>`}
function report(){return `${pagehead('REPORT WORKSPACE','확인한 내용을, 한 장의 보고서로.','답변과 근거를 모아 초안을 다듬고, 저장하거나 내려받으세요.',chip('검토용 초안','amber'))}<div class="report-layout"><section class="panel report-editor"><div class="section-line"><h2>보고서 초안</h2><span id="save-status" class="small muted">${state.saved?(state.engine==='backend'?'DB에 저장됨':'브라우저에 저장됨'):'편집 가능'}</span></div><label class="field" for="report-title">보고서 제목<input id="report-title" maxlength="120" value="${esc(state.report.title)}"/></label><label class="field" for="report-type">보고서 유형<select id="report-type">${['규정 검토','일일 운항','배출량 검토','종합 검토'].map(x=>`<option ${state.report.type===x?'selected':''}>${x}</option>`).join('')}</select></label><div class="section-line editor-label"><label for="report-text">내용</label><button class="text-btn" data-action="report-template">${ico('plus')} 기본 양식 추가</button></div><textarea id="report-text" placeholder="규정 검색 결과에서 ‘보고서에 담기’를 누르거나, 기본 양식을 추가해 시작하세요.">${esc(state.report.text)}</textarea><p id="report-error" class="field-error" role="alert"></p><div class="editor-actions">${btn(`${ico('download')} 내려받기 (.md)`,'download-report','secondary')}${btn(`${ico('check')} 초안 저장`,'save-report','primary')}</div><p class="small muted storage-note">${state.engine==='backend'?'실행 중인 서버의 DB에 저장됩니다. 다른 창에서 편집했다면 DB 초안을 다시 불러오세요.':'이 브라우저에만 저장됩니다.'} 저장과 내보내기는 검토용 초안이며 공식 승인이 아닙니다.</p><div class="backup-actions">${state.engine==='backend'?btn('DB 초안 불러오기','load-db-report'):''}${btn('초안 백업 (.json)','backup-report')}${btn('백업 불러오기','restore-report')}<input id="restore-file" type="file" accept="application/json,.json" hidden/></div><p class="small muted">이 기능은 현재 초안만 백업합니다. 문서·운항 DB·설정 전체 백업은 선내 시스템 구현 범위입니다.</p></section><aside class="report-aside"><section class="panel"><span class="task-icon green">${ico('book')}</span><h2>연결된 근거 <span class="count">${state.report.sources.length}</span></h2><p class="small muted">보고서와 함께 출처 정보가 내려받아집니다.</p>${state.report.sources.length?state.report.sources.map(id=>`<button class="report-source" data-doc="${id}">${ico('file')}<span><strong>${esc(DOCS[id].title)}</strong><small>${esc(DOCS[id].ref)}</small></span>${ico('chevron')}</button>`).join(''):'<div class="no-sources">아직 담은 근거가 없습니다.</div>'}<button class="btn secondary full" data-nav="regulation">근거 더 찾기 ${ico('arrow')}</button></section><div class="report-tip">${ico('info')}<div><strong>제출 전 확인해 주세요.</strong><p>샘플 수치와 가상 문서를 실제 자료로 교체하고, 담당자의 검토를 거쳐야 합니다.</p></div></div></aside></div>`}
function content(){if(state.page==='navigation')return navigationPage();if(state.page==='device')return devicePage();return state.page==='home'?home():state.page==='regulation'?regulation():state.page==='ask'?regulation(true):state.page==='briefing'?briefing():state.page==='carbon'?carbon():report()}
function render(){if(typeof unmountOperational==='function')unmountOperational();document.getElementById('app').innerHTML=shell();if(typeof mountOperational==='function')mountOperational();document.title=`${navs.find(x=>x[0]===state.page)?.[2]||'해,답'} · 해,답`}
function navigate(page){if(!navs.some(x=>x[0]===page))page='home';state.requestId++;state.loading=false;state.page=page;state.menu=false;state.error=null;if(location.hash!==`#${page}`)history.pushState(null,'',`#${page}`);render();window.scrollTo(0,0);document.getElementById('main').focus({preventScroll:true})}
function runScenario(id){if(id==='integrated'){state.query=state.language==='en'?'Show our emissions and applicable CII rules together':'우리 선박 배출량과 CII 규정을 함께 알려줘';state.filter='all';navigate('ask');search(state.query);return}if(id==='briefing'){navigate('briefing');return}if(!RULES[id])return;state.query=state.language==='en'?ENGLISH[id].query:RULES[id].query;state.filter='all';if(state.page!=='regulation'&&state.page!=='ask')navigate('regulation');search(state.query)}
async function search(query){
 if(state.engine==='backend')return backendSearch(query);
 state.query=query.trim();state.error=null;
 if(!state.query){state.result=null;state.error='empty';render();document.getElementById('query').focus();return}
 state.language=/[가-힣]/.test(state.query)?'ko':'en';
 const integrated=/(배출|운항|계산|emission|vessel|our ship)/i.test(state.query)&&/(규정|기준|함께|cii|rule)/i.test(state.query);
 const mode=state.sim;
 if(mode==='network'||mode==='noresults'||mode==='tool'||mode==='slow'||mode==='outdated')state.sim='normal';
 if(state.offline&&state.engine==='api'){state.result=null;state.error='offline';render();return}
 if(mode==='tool'||mode==='outdated'){state.result=null;state.error=mode;render();return}
 if(!integrated&&mode==='normal'&&state.page==='ask'){
  if(/운항|오늘|브리핑|속력|briefing|voyage/i.test(state.query)){navigate('briefing');return}
  if(/보고서|초안|report|draft/i.test(state.query)){navigate('report');return}
  if(/계산|배출량|calculate|emissions/i.test(state.query)){navigate('carbon');return}
 }
 let id=integrated?'integrated':/cii|탄소집약|등급|시정|seemp/i.test(state.query)?'cii':/점검표|전환|기록|체크리스트|checklist|changeover/i.test(state.query)?'checklist':/황|연료|eca|배출규제|sulph|sulfur|marpol|fuel|0\.1/i.test(state.query)?'sulfur':null;
 const request=++state.requestId;state.loading=true;state.result=null;state.longWait=mode==='slow';render();
 await new Promise(r=>setTimeout(r,mode==='slow'?1500:520));if(request!==state.requestId)return;
 state.loading=false;state.longWait=false;
 if(mode==='network')state.error='network';else if(!id||mode==='noresults')state.error='noresults';else{state.result=id;state.history=[{id,query:state.query},...state.history.filter(x=>x.id!==id)].slice(0,4);writeLocal('haedap-history',state.history)}render()
}

function openDoc(id,retry=false){const d=DOCS[id];if(!d)return;const dialog=document.getElementById('document-dialog');const fail=state.sim==='document'&&!retry;if(fail)state.sim='normal';else state.reviewed.add(id);dialog.innerHTML=`<div class="dialog-head"><span>${ico('book')} 근거 문서</span><button class="icon-btn" data-close="document-dialog" aria-label="문서 닫기">${ico('close')}</button></div>${fail?`<div class="error-state"><span class="error-symbol">${ico('alert')}</span><h2 id="doc-title">근거 문서를 불러오지 못했어요.</h2><p>문서 연결 오류를 재현했습니다. 다시 시도해 주세요.</p><button class="btn primary" data-doc-retry="${id}">다시 불러오기</button></div>`:`<div class="doc-body"><span class="badge ${d.url?'soft':'amber'}">${esc(d.category)}</span><h2 id="doc-title">${esc(d.title)}</h2><p class="muted">${esc(d.ref)}</p><dl class="doc-meta"><div><dt>버전 / 기준</dt><dd>${esc(d.version)}</dd></div><div><dt>문서 위치</dt><dd>${esc(d.location)}</dd></div><div><dt>적용 조건</dt><dd>${id==='sulfur'?'항로·적용 해역·연료·승인 설비 확인 필요':id==='cii'?'대상 선종·총톤수·평가연도·연간 자료 확인 필요':'HAE-01 가상 선박에 한정'}</dd></div><div><dt>개정 상태</dt><dd>${d.backend?'수집한 버전 · 최신 개정 여부 자동 확인 불가':(d.url?'확인일 기준 저장 요약 · 최신 개정 여부 자동 확인 불가':'샘플 버전 · 실제 승인 문서 아님')}</dd></div><div><dt>제공 형식</dt><dd>${d.backend?esc(d.category):(d.url?'공식 웹 안내의 한국어 요약':'흐름 검증용 가상 문서')}</dd></div></dl><div class="doc-page"><div class="doc-page-heading">${d.backend?(d.category==='가상 샘플 문서'?'SAMPLE DOCUMENT':'STORED DOCUMENT'):(d.url?'SOURCE SUMMARY':'DEMO DOCUMENT')}<span>해,답</span></div><h3>${esc(d.ref)}</h3>${d.body.map((p,i)=>`<p class="${i===0?'highlight':''}"><span class="paragraph-num">${String(i+1).padStart(2,'0')}</span>${esc(p)}</p>`).join('')}<div class="doc-page-footer">${d.backend&&d.category==='선내 문서'?'수집한 선내 문서 · 승인 상태와 적용 범위 확인 필요':(d.url?'저장 자료 · 원문은 아래 링크에서 확인':'SAMPLE ONLY · 가상 문서')}</div></div><p class="inline-note">${ico('info')}${esc(d.note)}</p>${d.url?`<a class="btn secondary full" href="${esc(d.url)}" target="_blank" rel="noopener noreferrer">출처 원문 열기 ${ico('external')}</a>`:''}<button class="btn primary full doc-add" data-add-doc="${id}">${ico('plus')} 이 근거를 보고서에 담기</button></div>`}`;if(!dialog.open)dialog.showModal()}
function addReport(text,ids,type){if(text&&!state.report.text.includes(text))state.report.text+=(state.report.text?'\n\n':'')+text;state.report.sources=[...new Set([...state.report.sources,...ids])];if(state.report.sources.length<=ids.length)state.report.type=type;state.saved=false;navigate('report');toast('내용과 출처를 보고서 초안에 담았습니다.')}
function captureReport(){const title=document.getElementById('report-title');if(title){state.report.title=title.value;state.report.type=document.getElementById('report-type').value;state.report.text=document.getElementById('report-text').value}}
function reportFile(){return `# ${state.report.title}\n\n유형: ${state.report.type}\n상태: 샘플 데이터 기반 검토용 초안\n\n${state.report.text}\n\n## 근거 문서\n${state.report.sources.map((id,i)=>{const d=DOCS[id];return `[${i+1}] ${d.title}\n${d.ref} | ${d.version}\n위치: ${d.location}\n${d.url||'가상 샘플 문서 · 공식 원문 없음'}`}).join('\n\n')}\n\n---\n해,답 인터랙티브 데모. 문서 검색 근거와 사용자 입력 계산을 포함할 수 있습니다. 운항 수치는 별도 검증이 필요합니다. 실제 운항 판단이나 공식 보고에 사용하지 마세요.\n`}
function validateReport(){captureReport();if(!state.report.title.trim()||!state.report.text.trim()){document.getElementById('report-error').textContent='제목과 내용을 모두 입력해 주세요.';return false}document.getElementById('report-error').textContent='';return true}
function demoSettings(){const d=document.getElementById('demo-dialog');d.innerHTML=`<div class="dialog-head"><span>${ico('settings')} 데모 상태 설정</span><button class="icon-btn" data-close="demo-dialog" aria-label="설정 닫기">${ico('close')}</button></div><div class="demo-body"><h2 id="demo-title">다른 상황도 확인해 보세요.</h2><p class="small muted">문서 검색은 로컬 서버에 연결됩니다. 샘플 모드에서는 기존 시나리오와 오류 상황을 체험할 수 있습니다.</p><form id="demo-form"><label class="radio-card"><input type="checkbox" id="backend-model" ${backend.useModel?'checked':''} ${backend.health?.llmConfigured?'':'disabled'}/><span><strong>검색 근거로 AI 답변 생성</strong><small>${backend.health?.llmConfigured?'질문과 검색 문단이 설정된 외부 모델로 전송됩니다.':'서버에 API 키와 모델을 설정하면 사용할 수 있습니다.'}</small></span></label><label class="field" for="engine">실행 방식<select id="engine" name="engine"><option value="backend" ${state.engine==='backend'?'selected':''}>문서 검색 + DB + 계산 도구</option><option value="local" ${state.engine==='local'?'selected':''}>선내 실행 방식 (샘플 응답)</option><option value="api" ${state.engine==='api'?'selected':''}>외부 API 방식 (샘플 응답)</option></select></label><label class="radio-card"><input type="checkbox" name="offline" ${state.offline?'checked':''}/><span><strong>외부망 차단 상황</strong><small>API 방식에서는 새 답변을 보류합니다. 저장 데이터 계산·초안 편집은 계속 가능합니다.</small></span></label><p class="small muted">아래 오류는 샘플 모드에서만 다음 조회에 한 번 재현됩니다.</p>${[['normal','정상 응답','준비된 시나리오를 정상적으로 조회합니다.'],['network','조회 연결 오류','검색 후 재시도 흐름을 확인합니다.'],['noresults','검색 결과 없음','근거가 없을 때의 안내를 확인합니다.'],['document','근거 문서 연결 오류','문서를 열 때 복구 흐름을 확인합니다.'],['tool','계산 도구 실패','계산 결과를 만들지 않고 재시도를 안내합니다.'],['outdated','구버전 문서만 존재','적용 판정을 보류하고 개정판 확인을 요청합니다.'],['slow','30초 초과 진행 안내','실제로 기다리지 않고 지연 안내를 재현합니다.']].map(([v,t,desc])=>`<label class="radio-card"><input type="radio" name="mode" value="${v}" ${state.sim===v?'checked':''}/><span><strong>${t}</strong><small>${desc}</small></span></label>`).join('')}<button type="submit" class="btn primary full">선택한 상태 적용</button></form></div>`;d.showModal()}
function action(name){switch(name){case 'add-backend-result':addBackendResult();break;case 'load-db-report':loadBackendReport();break;case 'backup-report':backupReport();break;case 'restore-report':document.getElementById('restore-file').click();break;case 'menu':state.menu=!state.menu;render();break;case 'close-menu':state.menu=false;render();break;case 'demo-settings':demoSettings();break;case 'retry':search(state.query);break;case 'sample-sulfur':state.filter='all';runScenario('sulfur');break;case 'add-rule':{if(state.result==='integrated'){addReport(integratedText(),['carbon','cii'],'종합 검토');break}const r=getRule();addReport(`## ${r.query}\n\n${r.summary}\n\n핵심 수치: ${r.metrics.map(x=>x.join(' ')).join(' / ')}\n\n확인 사항:\n${r.checks.map(x=>'- '+x).join('\n')}\n\n근거: ${r.docs.map(id=>DOCS[id].ref).join(', ')}`,r.docs,'규정 검토');break}case 'add-briefing':addReport('## 일일 운항 브리핑\n\n기준: 2026.09.17 12:00 KST (샘플)\nHAE-01 / V.026 / 부산 → 싱가포르\n24시간 항해 거리: 312 nm\n평균 속력: 13.0 kn\n연료 사용량: 24.8 t\nCO₂ 추정량: 77.23 t (환산계수 3.114 가정)\n도착 예정: 2026.09.20 12:00 KST\n\n다음 확인 사항: 연료 관련 서류와 일일 운항 기록 검토.\n실제 운항·기상 데이터 연결 전의 가상 기록입니다.',['noon'],'일일 운항');break;case 'reset-carbon':state.carbon={fuel:5400,factor:3.114,dwt:50000,distance:60000};state.calc=calculate();state.carbonError='';render();break;case 'reduce-fuel':state.carbon={fuel:4968,factor:3.114,dwt:50000,distance:60000};state.calc=calculate();state.carbonError='';render();toast('기본 연료 사용량을 8% 줄여 계산했습니다.');break;case 'add-carbon':{if(!captureCarbon())return;const c=state.carbon,v=calculate();addReport(`## 연간 배출량 검토 (가상 데이터)\n\n연료: ${c.fuel} t / 환산계수: ${c.factor}\n재화중량: ${c.dwt} DWT / 거리: ${c.distance} nm\nCO₂: ${v.emission.toFixed(2)} t\n단순 집약도: ${v.intensity.toFixed(2)} gCO₂/(DWT·nm)\n공식 CII 등급: 미산정\n\n선종별 기준선·보정계수·제외 항차 미반영. 공식 판정 및 실제 보고에 사용하지 않습니다.`,['carbon','cii'],'배출량 검토');break}case 'report-template':captureReport();state.report.text+=(state.report.text?'\n\n':'')+'## 검토 목적\n\n[작성해 주세요]\n\n## 주요 내용\n\n[핵심 수치와 확인한 내용을 작성해 주세요]\n\n## 추가 확인 사항\n\n- [담당자 / 확인 내용 / 예정일]\n\n## 검토자\n\n[성명 / 검토일]';state.saved=false;render();break;case 'save-report':if(state.engine==='backend'){saveBackendReport();break;}if(validateReport()&&writeLocal('haedap-report',state.report)){state.saved=true;document.getElementById('save-status').textContent='브라우저에 저장됨';toast('이 브라우저에 초안을 저장했습니다.')}break;case 'download-report':if(validateReport()){const url=URL.createObjectURL(new Blob([reportFile()],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='HAEDAP_report_draft.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('출처를 포함한 보고서 파일을 내려받았습니다.')}break}}
function captureCarbon(){const values={};for(const key of ['fuel','factor','dwt','distance']){const raw=document.getElementById(key)?.value;values[key]=raw===''?NaN:Number(raw)}const valid=Number.isFinite(values.fuel)&&values.fuel>=0&&values.fuel<=1e7&&Number.isFinite(values.factor)&&values.factor>0&&values.factor<=10&&Number.isFinite(values.dwt)&&values.dwt>0&&values.dwt<=1e7&&Number.isFinite(values.distance)&&values.distance>0&&values.distance<=1e7;if(!valid){state.carbonError='연료는 0 이상, 나머지는 0보다 큰 값을 입력해 주세요. 환산계수는 10 이하, 나머지는 1천만 이하입니다.';document.getElementById('carbon-validation').textContent=state.carbonError;return false}state.carbon=values;state.carbonError='';state.calc=calculate();return true}

function integratedText(){const v=calculate(),c=state.carbon;return `## 문서·운항 데이터 통합 검토 (샘플)\n\n선박: HAE-01 / 평가기간: 2026년 가상 연간 자료\n입력: 연료 ${c.fuel} t, 환산계수 ${c.factor}, DWT ${c.dwt}, 거리 ${c.distance} nm\nCO₂: ${v.emission.toFixed(2)} t / 단순 집약도: ${v.intensity.toFixed(2)} gCO₂/(DWT·nm)\n계산식: 연료 × 계수; CO₂ × 1,000,000 ÷ (DWT × 거리)\n계산식 버전: DEMO-CALC-1\n\n공식 CII 등급: 미산정. 선종별 요구 CII, 보정 조건과 검증된 연간 자료가 부족합니다.\n관련 기준: MARPOL Annex VI Regulation 28. 검증된 연간 등급 이력 확인 후 담당자 검토가 필요합니다.\n근거: DEMO-CARBON-2026 / IMO CII FAQ. 계수는 데모 가정입니다.`}
function integratedResult(){const c=state.carbon,v=calculate(),en=state.language==='en';return `<section class="result-card"><div class="result-heading"><span class="answer-icon">${ico('compass')}</span><div><div class="eyebrow">DATA + REGULATION</div><h2>${en?'Emissions and CII evidence, together.':'우리 선박 수치와 적용 기준을 함께 확인합니다.'}</h2></div>${chip(en?'Sample response':'샘플 통합 응답','soft')}</div>${metricsView([[en?'Annual CO₂':'연간 CO₂',v.emission.toFixed(2),'tCO₂'],[en?'Simple intensity':'단순 집약도',v.intensity.toFixed(2),'gCO₂/(DWT·nm)'],[en?'Official CII rating':'공식 CII 등급',en?'Not rated':'미산정',en?'Missing verified data':'검증 자료 부족']])}<section class="result-block"><div class="block-label"><span>02</span> ${en?'Summary · Applicability':'요약 · 적용 조건'}</div><p>${en?'HAE-01 uses fictional annual inputs. The figures above are arithmetic results, not a verified CII rating.':'HAE-01의 가상 연간 입력으로 계산한 결과입니다. 위 수치만으로 공식 CII 등급이나 규정 적합 여부를 판단할 수 없습니다.'} <button class="citation" data-doc="carbon">[1]</button></p><p>${en?'CII assessment needs verified annual data and the applicable requirements. Obtain the ship type, gross tonnage, rating-year baseline and correction conditions before review.':'CII 평가에는 검증된 연간 자료와 적용 기준이 필요합니다. 대상 선종·총톤수·평가연도별 기준선·보정 조건을 확보하고 담당자 검토를 요청하세요.'} <button class="citation" data-doc="cii">[2]</button></p><details class="formula"><summary>${en?'Inputs and calculation':'입력값·계산식 확인'}</summary><p>HAE-01 · 2026 (${en?'fictional annual dataset':'가상 연간 자료'})<br>${c.fuel} t × ${c.factor} = ${v.emission.toFixed(2)} tCO₂<br>${v.emission.toFixed(2)} × 1,000,000 ÷ (${c.dwt} × ${c.distance}) = ${v.intensity.toFixed(2)} gCO₂/(DWT·nm)<br>DEMO-CALC-1 · ${en?'Assumed conversion factor':'환산계수는 데모 가정'}</p></details><button class="text-btn" data-nav="carbon">${en?'Edit calculation inputs':'계산 입력값 수정'} ${ico('arrow')}</button></section>${sourceCards(['carbon','cii'])}<div class="result-footer"><span>${en?'Draft review required':'검토용 초안 · 담당자 확인 필요'}</span>${btn(en?'Add to draft':'보고서에 담기','add-rule','primary')}</div></section>`}
function backupReport(){if(!validateReport())return;const backup={format:'haedap-draft',version:1,createdAt:new Date().toISOString(),report:state.report};const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='HAEDAP_draft_backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('현재 초안을 백업했습니다.')}
function validateBackup(data){return data&&data.format==='haedap-draft'&&data.version===1&&typeof data.createdAt==='string'&&Number.isFinite(Date.parse(data.createdAt))&&data.report&&typeof data.report.title==='string'&&data.report.title.trim()&&data.report.title.length<=120&&typeof data.report.text==='string'&&data.report.text.length<=200000&&['규정 검토','일일 운항','배출량 검토','종합 검토'].includes(data.report.type)&&Array.isArray(data.report.sources)&&data.report.sources.every(x=>typeof x==='string'&&Object.hasOwn(DOCS,x))}
document.addEventListener('change',async e=>{if(e.target.id==='answer-language'){state.language=e.target.value;if(state.engine==='backend'&&state.query.trim())search(state.query);else render()}if(e.target.id==='restore-file'){const file=e.target.files[0];if(!file)return;try{if(file.size>1048576)throw new Error();const data=JSON.parse(await file.text());if(!validateBackup(data))throw new Error();if(!window.confirm(`백업 시각: ${data.createdAt}\n현재 초안을 이 백업으로 바꾸시겠습니까?`))return;state.report={title:data.report.title,type:data.report.type,text:data.report.text,sources:[...new Set(data.report.sources)]};state.saved=false;render();toast('백업을 불러왔습니다. 확인 후 초안을 저장하세요.')}catch{toast('올바른 해,답 초안 백업 파일이 아닙니다. 기존 내용은 유지했습니다.')}}});

document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;if(el.dataset.nav){captureReport();navigate(el.dataset.nav)}else if(el.dataset.action){action(el.dataset.action)}else if(el.dataset.scenario){runScenario(el.dataset.scenario)}else if(el.dataset.filter){state.filter=el.dataset.filter;if(state.engine==='backend'&&state.query.trim())search(state.query);else render()}else if(el.dataset.doc){openDoc(el.dataset.doc)}else if(el.dataset.close){document.getElementById(el.dataset.close).close();if(el.dataset.close==='document-dialog'){captureReport();render()}}else if(el.dataset.docRetry){openDoc(el.dataset.docRetry,true)}else if(el.dataset.addDoc){const id=el.dataset.addDoc;document.getElementById('document-dialog').close();captureReport();addReport('',[id],state.report.type)}else if(el.matches('a[href^="#"]')){e.preventDefault();if(el.getAttribute('href')==='#main'){document.getElementById('main').focus();return}captureReport();navigate(el.getAttribute('href').slice(1))}});
document.addEventListener('submit',e=>{if(e.target.id==='search-form'){e.preventDefault();search(document.getElementById('query').value)}if(e.target.id==='carbon-form'){e.preventDefault();if(state.engine==='backend'){calculateBackendCarbon();return;}if(captureCarbon()){render();toast('입력한 수치로 다시 계산했습니다.')}}if(e.target.id==='demo-form'){e.preventDefault();const form=new FormData(e.target);state.requestId++;state.loading=false;state.result=null;state.error=null;state.sim=form.get('mode');state.engine=form.get('engine');state.offline=form.has('offline');render();document.getElementById('demo-dialog').close();toast(state.sim==='normal'?'정상 응답으로 설정했습니다.':'다음 조회에 선택한 오류를 적용합니다.')}});
document.addEventListener('input',e=>{if(e.target.id==='query')state.query=e.target.value;if(['report-title','report-text','report-type'].includes(e.target.id)){captureReport();state.saved=false;const el=document.getElementById('save-status');if(el)el.textContent='저장하지 않은 변경사항'}});
window.addEventListener('popstate',()=>navigate(location.hash.slice(1)||'home'));
for(const id of ['document-dialog','demo-dialog'])document.getElementById(id).addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close()}});
document.getElementById('document-dialog').addEventListener('close',()=>{captureReport();render()});
state.page=navs.some(x=>x[0]===location.hash.slice(1))?location.hash.slice(1):'home';render();

initializeBackend();
