import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {once} from 'node:events';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {openDatabase,importDocuments,saveReport} from '../backend/db.mjs';
import {createApi} from '../backend/api.mjs';
const seed=JSON.parse(readFileSync(new URL('../knowledge/seed.json',import.meta.url),'utf8'));
async function fixture(t){const dir=mkdtempSync(join(tmpdir(),'haedap-core-')),db=openDatabase(join(dir,'test.sqlite'));importDocuments(db,seed);saveReport(db,{title:'이전 공용 초안',type:'규정 검토',text:'기존 내용을 보존합니다.',sources:[],version:0});const api=createApi(db,{backupDir:join(dir,'backups'),env:{}}),server=http.createServer((req,res)=>api(req,res,new URL(req.url,'http://localhost').pathname));server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port;t.after(async()=>{await new Promise(r=>server.close(r));db.close();rmSync(dir,{recursive:true,force:true});});
 function client(){const cookies=new Map();let token='';return {async call(path,body){const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Cookie:[...cookies].map(([k,v])=>k+'='+v).join('; '),'Content-Type':'application/json','X-Haedap-Token':token},body:body===undefined?undefined:JSON.stringify(body)});for(const header of r.headers.getSetCookie()){const [k,v]=header.split(';')[0].split('=');if(v)cookies.set(k,v);else cookies.delete(k);}const data=await r.json();if(path==='/api/health')token=data.csrfToken;return {...data,status:r.status};},async ok(path,body){const r=await this.call(path,body);assert.equal(r.status,200,JSON.stringify(r));return r;}};}
 const admin=client();await admin.ok('/api/health');await admin.ok('/api/auth/login',{username:'admin',password:'1234'});return {admin,client,db};}
const ship={id:'vessel-1',name:'검증선',type:'벌크선',dwt:1000,imo:'1234567',version:0};
const row={ship:'vessel-1',date:'2026-09-28',fuel:10,factor:3,distance:100,speed:10,fuelType:'검증 연료',position:'항만 A',voyage:'TEST-1',draft:7,weather:'맑음',engineHours:24};
const document={id:'secure-manual',title:'제한 문서',kind:'onboard',url:null,reference:'제1조',version:'1',reviewedAt:'2026-09-30',sections:[{page:7,heading:'규정',text:'실험용 비밀 식별자 헬리오스는 연료 소비량 10톤 이하를 기준으로 사용한다.'}]};
test('authentication, document access enforcement before search, PDF/page provenance, old draft migration',async t=>{const {admin,client}=await fixture(t),guest=client();await guest.ok('/api/health');assert.equal((await guest.call('/api/documents')).status,200);assert.equal((await guest.call('/api/ask',{question:'헬리오스'})).status,200);
 assert.ok((await admin.ok('/api/reports')).reports.some(r=>r.id==='current'));
 const {user}=await admin.ok('/api/users',{username:'viewer',name:'열람자',password:'viewer-password',role:'viewer',active:true});const reader=client();await reader.ok('/api/health');assert.equal((await reader.call('/api/auth/login',{username:'viewer',password:'viewer-password'})).status,403);
 await admin.ok('/api/changes',{kind:'document.save',payload:{document,expectedId:'',meta:{scope:'admin',status:'active',issuedAt:'2026-01-01',revisedAt:'2026-09-01'},file:{name:'test.pdf',base64:Buffer.from('%PDF-1.4\nfixture').toString('base64')}}});
 const docs=(await admin.ok('/api/documents')).documents,d=docs.find(d=>d.logical_id==='secure-manual');assert.equal(d.sections[0].page,7);assert.equal(d.hasPdf,true);
 assert.ok(!(await reader.ok('/api/documents')).documents.some(x=>x.id===d.id));assert.equal((await reader.call('/api/users')).status,403);assert.equal((await reader.call('/api/backups')).status,403);assert.equal((await reader.call('/api/changes/review',{id:'unknown',decision:'approve'})).status,403);
 assert.equal((await reader.ok('/api/ask',{question:'헬리오스'})).evidence.length,0);const answer=await admin.ok('/api/ask',{question:'헬리오스'});assert.equal(answer.evidence[0].page,7);
 const report=(await admin.ok('/api/reports',{title:'제한 근거 보고서',type:'규정 검토',text:'제한 내용',sources:[d.id],version:0})).report;assert.equal((await reader.call('/api/reports/'+report.id)).status,404);
 await admin.ok('/api/users',{...user,active:false,password:''});assert.equal((await reader.call('/api/documents')).status,200);
});
test('operation CRUD, transactional CSV validation, administrator-only immediate writes, stale edits and natural-language summary',async t=>{const {admin,client}=await fixture(t);await admin.ok('/api/changes',{kind:'ship.save',payload:ship});const operator=client();await operator.ok('/api/health');
 assert.equal((await operator.call('/api/changes',{kind:'operation.save',payload:row})).status,403);assert.equal((await admin.ok('/api/operations')).records.length,0);await admin.ok('/api/changes',{kind:'operation.save',payload:row});let record=(await admin.ok('/api/operations')).records[0];assert.equal(record.fuel,10);
 assert.equal((await admin.call('/api/changes',{kind:'operation.import',payload:{rows:[{...row,date:'2026-09-29'},{...row,date:'2026-09-30',fuel:-1}]}})).status,400);assert.equal((await admin.ok('/api/operations')).records.length,1);
 await admin.ok('/api/changes',{kind:'operation.save',payload:{...record,fuel:11}});assert.equal((await admin.call('/api/changes',{kind:'operation.save',payload:{...record,fuel:12}})).status,409);
 const answer=await admin.ok('/api/ask',{question:'선택 선박 운항 추이 분석',task:'auto',context:{ship:ship.id,from:'2026-09-01',to:'2026-09-30'}});assert.equal(answer.operations.fuel,11);assert.equal(answer.operations.emission,33);assert.equal(answer.compliance.status,'unknown');assert.equal(answer.operations.cii.rating,null);
 const bad=await admin.ok('/api/operations/validate',{rows:[{...row,date:'2026-09-29',fuel:100}]});assert.equal(bad.valid,false);assert.match(bad.errors[0].message,/점검 사유/);
 record=(await admin.ok('/api/operations')).records[0];await admin.ok('/api/changes',{kind:'operation.delete',payload:{id:record.id,version:record.version}});assert.equal((await admin.ok('/api/operations')).records.length,0);
});
test('multiple Noon/MRV drafts, optimistic saving, submission approval/locking, query history and logs',async t=>{const {admin}=await fixture(t);await admin.ok('/api/changes',{kind:'ship.save',payload:ship});await admin.ok('/api/changes',{kind:'operation.import',payload:{rows:[row,{...row,date:'2026-09-29',fuel:12}]}});
 const context={ship:ship.id,from:'2026-09-01',to:'2026-09-30'};const a=(await admin.ok('/api/reports/generate',{...context,template:'noon'})).report,b=(await admin.ok('/api/reports/generate',{...context,template:'mrv'})).report;
 assert.notEqual(a.id,b.id);assert.match(a.text,/연료 합계: 12 t/);assert.match(b.text,/연료 합계: 22 t/);assert.equal((await admin.ok('/api/reports/'+a.id)).report.title,a.title);assert.equal((await admin.ok('/api/reports/'+b.id)).report.title,b.title);
 const saved=(await admin.ok('/api/reports',{...a,text:a.text+'\n검토 완료'})).report;assert.equal((await admin.call('/api/reports',a)).status,409);
 const request=await admin.ok('/api/reports/submit',{id:saved.id,version:saved.version});assert.equal((await admin.call('/api/reports',saved)).status,400);await admin.ok('/api/changes/review',{id:request.id,decision:'approve'});assert.equal((await admin.ok('/api/reports/'+saved.id)).report.status,'approved');
 await admin.ok('/api/ask',{question:'연료 황 함유량 기준'});const history=(await admin.ok('/api/history')).history;assert.ok(history[0].answer.statements.length>0);assert.match(history[0].answer.statements[0].text,/0.50%/);assert.ok((await admin.ok('/api/logs')).logs.some(l=>l.category==='query'));assert.ok((await admin.ok('/api/logs')).logs.some(l=>l.category==='error'));
});
test('full backup/restore preserves documents, PDF, operations, reports and permissions, invalidates sessions',async t=>{const {admin,db}=await fixture(t);await admin.ok('/api/changes',{kind:'ship.save',payload:ship});await admin.ok('/api/changes',{kind:'operation.save',payload:row});await admin.ok('/api/changes',{kind:'document.save',payload:{document,expectedId:'',meta:{scope:'operator',status:'active'},file:{name:'fixture.pdf',base64:Buffer.from('%PDF-1.4\ntest').toString('base64')}}});
 const original=(await admin.ok('/api/operations')).records[0],backup=(await admin.ok('/api/backups',{})).backup;await admin.ok('/api/changes',{kind:'operation.delete',payload:{id:original.id,version:original.version}});const doc=(await admin.ok('/api/documents')).documents.find(d=>d.logical_id===document.id);await admin.ok('/api/changes',{kind:'document.delete',payload:{id:doc.id}});
 assert.equal((await admin.call('/api/backups/restore',{id:backup.id,confirm:'no'})).status,400);await admin.ok('/api/backups/restore',{id:backup.id,confirm:'복구'});assert.equal((await admin.ok('/api/health')).user.role,'guest');assert.equal((await admin.call('/api/backups')).status,403);await admin.ok('/api/auth/login',{username:'admin',password:'1234'});assert.equal((await admin.ok('/api/operations')).records[0].fuel,10);const restored=(await admin.ok('/api/documents')).documents.find(d=>d.id===doc.id);assert.equal(restored.hasPdf,true);assert.equal(restored.meta.scope,'operator');assert.equal((await admin.ok('/api/ask',{question:'헬리오스'})).evidence[0].page,7);assert.ok((await admin.ok('/api/backups')).backups.some(b=>b.label==='복구 직전 자동 보관'));assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');
});
test('criterion comparison covers met/unmet/unknown and invalid source rejection',async t=>{const {admin}=await fixture(t);await admin.ok('/api/changes',{kind:'ship.save',payload:ship});await admin.ok('/api/changes',{kind:'operation.save',payload:row});await admin.ok('/api/changes',{kind:'document.save',payload:{document,expectedId:'',meta:{scope:'all',status:'active'}}});const doc=(await admin.ok('/api/documents')).documents.find(d=>d.logical_id===document.id),chunk=doc.sections[0];
 const body={question:'운항 기록 기준 비교',task:'integrated',context:{ship:ship.id,from:'2026-09-01',to:'2026-09-30'},criterion:{documentId:doc.id,chunkId:chunk.id,quote:chunk.text,confirmed:true,metric:'fuel',operator:'lte',limit:10}};
 assert.equal((await admin.ok('/api/ask',body)).compliance.status,'met');assert.equal((await admin.ok('/api/ask',{...body,criterion:{...body.criterion,limit:9}})).compliance.status,'unmet');assert.equal((await admin.ok('/api/ask',{...body,criterion:null})).compliance.status,'unknown');assert.equal((await admin.call('/api/ask',{...body,criterion:{...body.criterion,quote:'만들어낸 근거 문장입니다.'}})).status,400);
});
test('backup imports are verified and daily backup runs once; CSV rejects within-batch anomalies',async t=>{const {admin,db}=await fixture(t);await admin.ok('/api/changes',{kind:'ship.save',payload:ship});const check=await admin.ok('/api/operations/validate',{rows:[row,{...row,date:'2026-09-29',fuel:100}]});assert.equal(check.valid,false);assert.equal(check.errors[0].row,2);
 const b=(await admin.ok('/api/backups',{})).backup,payload=await admin.ok('/api/backups/'+b.id);delete payload.status;const imported=await admin.ok('/api/backups/import',payload);assert.notEqual(imported.backup.id,b.id);assert.equal((await admin.call('/api/backups/import',{...payload,checksum:'bad'})).status,400);
 await admin.ok('/api/backups/settings',{autoBackup:'off'});assert.equal((await admin.ok('/api/backups')).autoBackup,'off');
 const {automaticBackup}=await import('../backend/workspace.mjs');const temp=mkdtempSync(join(tmpdir(),'haedap-auto-'));t.after(()=>rmSync(temp,{recursive:true,force:true}));await admin.ok('/api/backups/settings',{autoBackup:'daily'});automaticBackup(db,temp);const count=db.prepare("SELECT count(*) n FROM audit WHERE actor='자동 백업'").get().n;automaticBackup(db,temp);assert.equal(db.prepare("SELECT count(*) n FROM audit WHERE actor='자동 백업'").get().n,count);assert.equal(count,1);
});

test('public access, fixed administrator login/logout, private guest drafts and server-side management guards',async t=>{
 const {admin,client,db}=await fixture(t),guest=client(),other=client();
 const initial=await guest.ok('/api/health');assert.equal(initial.user.role,'guest');assert.equal(initial.setupRequired,false);assert.equal(initial.authenticated,false);
 await other.ok('/api/health');assert.notEqual((await other.ok('/api/health')).user.id,initial.user.id);
 assert.equal((await guest.call('/api/auth/login',{username:'admin',password:'wrong'})).status,401);
 assert.equal((await guest.call('/api/auth/setup',{username:'hacker',password:'1234'})).status,410);
 for(const path of ['/api/users','/api/logs','/api/backups','/api/changes'])assert.equal((await guest.call(path)).status,403,path);
 for(const [path,body] of [['/api/users',{username:'newadmin',name:'new',role:'admin',password:'long-password'}],['/api/backups',{}],['/api/backups/restore',{id:'x',confirm:'복구'}],['/api/backups/settings',{autoBackup:'off'}],['/api/changes/review',{id:'x',decision:'approve'}],['/api/operations/example',{}]])assert.equal((await guest.call(path,body)).status,403,path);
 assert.equal((await guest.call('/api/changes',{kind:'ship.save',payload:ship})).status,403);await admin.ok('/api/changes',{kind:'ship.save',payload:ship});await admin.ok('/api/changes',{kind:'operation.save',payload:row});
 assert.equal((await guest.ok('/api/tools/calculate_emissions',{fuel:10,factor:3,dwt:1000,distance:100})).result.emission,30);
 const draft=(await guest.ok('/api/reports',{title:'일반 사용자 초안',type:'규정 검토',text:'내 초안',sources:[],version:0})).report;
 assert.equal((await other.call('/api/reports/'+draft.id)).status,404);assert.equal((await other.call('/api/reports',{...draft,text:'가로채기'})).status,403);
 await guest.ok('/api/ask',{question:'황 함유량 기준'});assert.equal((await guest.ok('/api/history')).history.length,1);assert.equal((await other.ok('/api/history')).history.length,0);
 const generated=(await guest.ok('/api/reports/generate',{template:'noon',ship:ship.id,from:'2026-09-01',to:'2026-09-30'})).report;assert.equal(generated.owner,initial.user.id);
 const submitted=await guest.ok('/api/reports/submit',{id:generated.id,version:generated.version});await admin.ok('/api/changes/review',{id:submitted.id,decision:'approve'});assert.equal((await other.ok('/api/reports/'+generated.id)).report.status,'approved');
 await guest.ok('/api/auth/login',{username:'admin',password:'1234'});assert.equal((await guest.ok('/api/health')).authenticated,true);
 const adminDraft=(await guest.ok('/api/reports',{title:'관리자 초안',type:'규정 검토',text:'관리자 내용',sources:[],version:0})).report;
 const fixed=(await guest.ok('/api/users')).users.find(u=>u.username==='admin');assert.equal((await guest.call('/api/users',{...fixed,password:'changed-password'})).status,403);
 await guest.ok('/api/auth/logout',{});assert.equal((await guest.ok('/api/health')).user.id,initial.user.id);assert.equal((await guest.call('/api/logs')).status,403);assert.equal((await guest.call('/api/reports/'+adminDraft.id)).status,404);assert.equal((await guest.ok('/api/reports/'+draft.id)).report.text,'내 초안');
 await guest.ok('/api/auth/login',{username:'admin',password:'1234'});assert.equal((await guest.ok('/api/health')).user.role,'admin');
});

test('public visitor cannot overwrite a restricted document by reusing its logical ID',async t=>{
 const {admin,client}=await fixture(t),guest=client();await guest.ok('/api/health');
 const saved=await admin.ok('/api/changes',{kind:'document.save',payload:{document,expectedId:'',meta:{scope:'admin',status:'active'}}});
 const id=saved.result.id;
 for(const scope of ['all','operator','admin'])assert.equal((await guest.call('/api/changes',{kind:'document.save',payload:{document:{...document,version:'2'},meta:{scope,status:'active'}}})).status,403);
 assert.equal((await guest.call('/api/changes',{kind:'document.delete',payload:{id}})).status,403);
 assert.equal((await guest.ok('/api/search',{question:'헬리오스'})).evidence.length,0);
 assert.equal((await admin.ok('/api/documents')).documents.find(d=>d.id===id).meta.scope,'admin');
});

test('existing database migration preserves ownership and installs admin / 1234 only once',async t=>{
 const {initializeWorkspace,initializePublicAccess,saveUser,authenticate}=await import('../backend/workspace.mjs');
 const dir=mkdtempSync(join(tmpdir(),'haedap-migration-')),file=join(dir,'db.sqlite');let db=openDatabase(file);t.after(()=>{db.close();rmSync(dir,{recursive:true,force:true});});
 initializeWorkspace(db);const old=saveUser(db,null,{username:'admin',name:'기존 관리자',password:'previous-password'},true);
 saveReport(db,{title:'이전 보고서',type:'규정 검토',text:'보존',sources:[],version:0});initializePublicAccess(db);
 const current=authenticate(db,'admin','1234');assert.equal(current.id,old.id);assert.equal(current.name,old.name);assert.equal(current.version,old.version+1);assert.equal(db.prepare("SELECT owner FROM report_meta WHERE id='current'").get().owner,old.id);
 assert.throws(()=>authenticate(db,'admin','previous-password'));const hash=db.prepare('SELECT password FROM users WHERE id=?').get(old.id).password;assert.notEqual(hash,'1234');
 db.close();db=openDatabase(file);initializeWorkspace(db);initializePublicAccess(db);assert.equal(authenticate(db,'admin','1234').version,current.version);assert.equal(db.prepare('SELECT password FROM users WHERE id=?').get(old.id).password,hash);
});

test('only administrators can mutate documents, vessels and records; saves and deletes apply immediately',async t=>{
 const {admin,client,db}=await fixture(t),guest=client();await guest.ok('/api/health');
 const added=await admin.ok('/api/changes',{kind:'document.save',payload:{document,expectedId:'',meta:{scope:'all',status:'active'}}});
 const first=(await guest.ok('/api/documents')).documents.find(d=>d.id===added.result.id);assert.ok(first);
 const revised={document:{...document,version:'2',title:'즉시 개정한 문서'},expectedId:first.id,expectedMetaRevision:first.meta.revision,meta:{scope:'all',status:'active'}};
 const denied=[['document.save',{document:{...document,id:'new-public'},expectedId:'',meta:{scope:'all'}}],['document.save',revised],['document.delete',{id:first.id}],['ship.save',ship],['operation.save',row],['operation.import',{rows:[row]}],['operation.delete',{id:'any',version:1}]];
 const count=db.prepare('SELECT count(*) n FROM changes').get().n;
 for(const [kind,payload] of denied)assert.equal((await guest.call('/api/changes',{kind,payload})).status,403,kind);
 assert.equal((await guest.call('/api/operations/validate',{rows:[row]})).status,403);
 assert.equal(db.prepare('SELECT count(*) n FROM changes').get().n,count);
 const updated=await admin.ok('/api/changes',{kind:'document.save',payload:revised});
 assert.equal(db.prepare('SELECT status FROM changes WHERE id=?').get(updated.id).status,'approved');
 const current=(await guest.ok('/api/documents')).documents.find(d=>d.id===updated.result.id);assert.equal(current.active,true);assert.equal(current.title,'즉시 개정한 문서');
 await admin.ok('/api/changes',{kind:'document.delete',payload:{id:current.id}});assert.ok(!(await guest.ok('/api/documents')).documents.some(d=>d.logical_id===document.id));assert.equal((await guest.ok('/api/search',{question:'헬리오스'})).evidence.length,0);
 await admin.ok('/api/changes',{kind:'ship.save',payload:ship});await admin.ok('/api/changes',{kind:'operation.save',payload:row});
 let record=(await guest.ok('/api/operations')).records[0];assert.equal(record.fuel,10);
 assert.equal((await guest.call('/api/changes',{kind:'operation.save',payload:{...record,fuel:11}})).status,403);
 assert.equal((await guest.call('/api/changes',{kind:'operation.delete',payload:{id:record.id,version:record.version}})).status,403);
 await admin.ok('/api/changes',{kind:'operation.save',payload:{...record,fuel:11}});record=(await guest.ok('/api/operations')).records[0];assert.equal(record.fuel,11);
 await admin.ok('/api/changes',{kind:'operation.delete',payload:{id:record.id,version:record.version}});assert.equal((await guest.ok('/api/operations')).records.length,0);
 assert.equal(db.prepare("SELECT count(*) n FROM changes WHERE status='pending'").get().n,0);
 assert.ok((await admin.ok('/api/logs')).logs.some(l=>l.action==='변경 즉시 반영'));
 await admin.ok('/api/auth/logout',{});assert.equal((await admin.call('/api/changes',{kind:'ship.save',payload:{...ship,id:'after-logout'}})).status,403);
});
