'use client';
import {useEffect,useState} from 'react';

const TABS=[['ask','통합 질의'],['voyage','운항 데이터'],['documents','문서·근거'],['reports','보고서'],['history','작업 이력'],['admin','관리']];
const ROLES={admin:'관리자',captain:'선장·담당자',crew:'일반 사용자'};
const WARN={LLM_NOT_CONFIGURED:'모델이 설정되지 않아 문서 원문과 Python 계산 결과를 표시합니다.',LLM_ROUTING_FAILED_RULE_FALLBACK:'모델 연결에 실패해 규칙 기반으로 처리했습니다.',LLM_FAILED_EXTRACTIVE_FALLBACK:'생성 답변을 검증하지 못해 원문 근거로 전환했습니다.',VECTOR_UNAVAILABLE_BM25_ONLY:'벡터 색인을 사용할 수 없어 BM25 검색만 사용했습니다.',NO_VOYAGE_DATA:'선택한 선박·기간에 저장된 운항 데이터가 없습니다.'};
const sampleRecord={date:'2026-09-18',voyage:'026',status:'Under way',latitude:27.3,longitude:120.6,speed_kn:13,distance_nm:312,fuel_t:25,factor:3.114,engine_hours:24,draft_m:10,weather:'Fair'};
const docTemplate={logical_id:'training-guide',title:'교육용 운항 안내',version:'1.0',kind:'sample',issuer:'교육 자료',applicability:'가상 선박 교육용',restricted:false,vessels:[],sections:[{page:1,section:'1. 운항 기록',text:'교육용 가상 문서입니다. 운항 기록은 담당자가 입력값과 단위를 확인한 후 저장합니다.'}]};
function Stat({label,value,unit}){return <div className="stat"><span>{label}</span><strong>{Number(value||0).toLocaleString('ko-KR',{maximumFractionDigits:3})}<small>{unit}</small></strong></div>;}
function Evidence({items}){return <div className="evidence">{items.map(e=><details key={e.id}><summary>{e.title} <span>v{e.version} · {e.page?`p.${e.page}`:'페이지 미제공'} · {e.section}</span></summary><p className="preserve">{e.text}</p><p className="muted">{e.metadata?.issuer} · {e.metadata?.applicability} · {e.metadata?.kind==='sample'?'가상 자료':''}</p>{e.metadata?.source_url?.startsWith('https://')&&<a href={e.metadata.source_url} target="_blank" rel="noreferrer">공식 원문 열기 ↗</a>}</details>)}</div>;}
function Metrics({data}){if(!data)return null;const max=Math.max(...data.series.map(x=>x.fuel_t),1);return <><div className="stats"><Stat label="연료 사용량" value={data.fuel_t} unit="t"/><Stat label="CO₂ 배출량" value={data.emission_t} unit="tCO₂"/><Stat label="항해 거리" value={data.distance_nm} unit="nm"/><Stat label="기간 탄소집약도" value={data.intensity} unit="gCO₂/(DWT·nm)"/></div><div className="chart" aria-label="날짜별 연료 사용량">{data.series.map(p=><div key={p.date} className="barrow"><span>{p.date}</span><div><i style={{width:`${p.fuel_t/max*100}%`}}/></div><b>{p.fuel_t.toFixed(2)} t</b></div>)}</div><p className="notice">{data.notice}</p>{data.anomalies.map((a,i)=><p className="warning" key={i}>{a.date}: {a.message}</p>)}<details><summary>계산식·원본 입력·버전 확인</summary><pre>{JSON.stringify({formula:data.formula,version:data.version,inputs:data.inputs},null,2)}</pre></details></>;}

export default function Home(){
 const [user,setUser]=useState(null),[csrf,setCsrf]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[long,setLong]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [tab,setTab]=useState('ask'),[health,setHealth]=useState(null),[vessels,setVessels]=useState([]),[vessel,setVessel]=useState('HAE-01'),[start,setStart]=useState('2026-09-11'),[end,setEnd]=useState('2026-09-17');
 const [question,setQuestion]=useState('현재 선박의 배출량과 관련 IMO 규정을 알려줘'),[language,setLanguage]=useState('auto'),[useModel,setUseModel]=useState(false),[answer,setAnswer]=useState(null);
 const [records,setRecords]=useState([]),[metric,setMetric]=useState(null),[compare,setCompare]=useState(null),[recordJson,setRecordJson]=useState(JSON.stringify(sampleRecord,null,2)),[editRecord,setEditRecord]=useState(null);
 const [documents,setDocuments]=useState([]),[doc,setDoc]=useState(null),[docJson,setDocJson]=useState(JSON.stringify(docTemplate,null,2));
 const [reports,setReports]=useState([]),[report,setReport]=useState(null),[kind,setKind]=useState('Noon Report'),[history,setHistory]=useState([]),[accounts,setAccounts]=useState([]);
 const editable=user?.role==='admin'||user?.role==='captain';
 const scope={vessel_id:vessel,start,end};
 async function api(path,body,method){const multipart=body instanceof FormData;const res=await fetch('/api'+path,{method:method||(body?'POST':'GET'),headers:{...(body&&!multipart?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},body:body?(multipart?body:JSON.stringify(body)):undefined});const data=await res.json();if(!res.ok){if(res.status===401)setUser(null);throw new Error(typeof data.detail==='string'?data.detail:'입력 형식과 필수 항목을 확인해 주세요.');}return data;}
 async function run(fn){setError('');setMessage('');setBusy(true);setLong(false);const timer=setTimeout(()=>setLong(true),15000);try{await fn();}catch(e){setError(e.message);}finally{clearTimeout(timer);setBusy(false);setLong(false);}}
 async function refresh(){const [vs,ds,rs,h]=await Promise.all([api('/vessels'),api('/documents'),api('/reports'),api('/health')]);setVessels(vs);if(vs.length&&!vs.some(v=>v.id===vessel))setVessel(vs[0].id);setDocuments(ds);setReports(rs);setHealth(h);}
 useEffect(()=>{(async()=>{try{const me=await api('/me');setUser(me.user);setCsrf(me.csrf);}catch{}finally{setLoading(false);}})();},[]);
 useEffect(()=>{if(user)run(refresh);},[user?.id]);
 useEffect(()=>{setAnswer(null);setMetric(null);setCompare(null);setRecords([]);},[vessel,start,end]);
 async function changeTab(next){setTab(next);setError('');if(next==='history')await run(async()=>setHistory(await api('/history')));if(next==='admin')await run(async()=>setAccounts(await api('/users')));if(next==='reports')await run(async()=>setReports(await api('/reports')));}
 async function loadVoyage(){const data=await api('/records?'+new URLSearchParams(scope));setRecords(data.records);setMetric(data.records.length?await api('/metrics',scope):null);if(!data.records.length)setMessage('선택한 기간에 저장된 운항 기록이 없습니다.');}
 async function createDraft(){const r=await api('/reports',{...scope,kind,question});setReport(r);setReports(await api('/reports'));setTab('reports');setMessage('보고서 초안을 저장했습니다. 담당자 검토 전에는 공식 보고서가 아닙니다.');}
 if(loading)return <main className="login"><p>워크스페이스 연결 중…</p></main>;
 if(!user)return <main className="login"><div className="login-brand">해,답<span>MARITIME WORKSPACE</span></div><section className="login-card"><span className="eyebrow">WELCOME ABOARD</span><h1>근거로 답하고,<br/>데이터로 확인하세요.</h1><p>선내 문서와 운항 데이터를 하나의 흐름으로.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const d=await api('/login',Object.fromEntries(f));setUser(d.user);setCsrf(d.csrf);});}}><label>사용자 이름<input name="username" autoComplete="username" required defaultValue="captain"/></label><label>비밀번호<input name="password" type="password" autoComplete="current-password" required/></label><button className="primary" disabled={busy}>{busy?'확인 중…':'워크스페이스 시작 →'}</button></form>{error&&<p role="alert" className="error">{error}</p>}<p className="muted small">처음 실행한 경우 프로젝트의 <code>data/initial-login.txt</code>에서 개발 계정을 확인하세요.</p></section></main>;
 return <div className="shell"><aside><div className="brand">해,답<span>YOUR MARITIME COPILOT</span></div><p className="eyebrow">WORKSPACE</p><nav>{TABS.filter(([id])=>id!=='admin'||user.role==='admin').map(([id,name],i)=><button key={id} disabled={busy} className={tab===id?'active':''} onClick={()=>changeTab(id)}><span>0{i+1}</span>{name}</button>)}</nav><div className="account"><b>{user.username}</b><span>{ROLES[user.role]}</span><button onClick={()=>run(async()=>{await api('/logout',{});setUser(null);setCsrf('');})}>로그아웃</button></div></aside><div className="workspace"><header><span>선원 업무 워크스페이스 / {TABS.find(x=>x[0]===tab)?.[1]}</span><span className="badge">{health?.ok?'● 연결됨':'연결 확인 중'}</span></header><main><div className="intro"><div><span className="eyebrow">ON BOARD, IN CONTROL</span><h1>{TABS.find(x=>x[0]===tab)?.[1]}</h1><p>질문에서 근거, 계산에서 보고서까지.</p></div><span className="pill">{vessels.find(x=>x.id===vessel)?.sample?'가상 운항 데이터':'등록 운항 데이터'}</span></div><section className="scope"><label>선박<select disabled={busy} value={vessel} onChange={e=>setVessel(e.target.value)}>{vessels.map(v=><option key={v.id} value={v.id}>{v.name} · {v.id}</option>)}</select></label><label>시작일<input type="date" disabled={busy} value={start} onChange={e=>setStart(e.target.value)}/></label><label>종료일<input type="date" disabled={busy} value={end} onChange={e=>setEnd(e.target.value)}/></label><span className="muted small">조회·계산은 위 선박과 기간을 기준으로 수행합니다.</span></section>
 {busy&&<p role="status" className="notice">{long?'15초 이상 소요되고 있습니다. 문서 검색·모델 처리를 계속 진행 중입니다.':'처리 중입니다…'}</p>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}
 <fieldset disabled={busy} className="content">
 {tab==='ask'&&<><section className="panel"><h2>무엇을 확인할까요?</h2><form onSubmit={e=>{e.preventDefault();run(async()=>setAnswer(await api('/ask',{...scope,question,language,use_model:useModel})));}}><label>질문<textarea value={question} onChange={e=>setQuestion(e.target.value)} rows={3} maxLength={2000} required/></label><div className="row"><label>답변 언어<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="auto">자동 감지</option><option value="ko">한국어</option><option value="en">English</option></select></label><label className="check"><input type="checkbox" checked={useModel} onChange={e=>setUseModel(e.target.checked)} disabled={!health?.llm}/>근거 기반 AI 답변 {health?.llm?'':'(모델 미설정)'}</label><button className="primary">질문하기 →</button></div></form><div className="chips">{['현재 선박의 배출량과 관련 IMO 규정을 알려줘','선박 운항 상태와 항차 정보를 조회해줘','Noon Report 초안을 만들어줘','What is the fuel sulphur limit in an ECA?'].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}</button>)}</div></section>{answer&&<section className="panel"><div className="row"><h2>{answer.insufficient?'확인 가능한 근거가 부족합니다.':'조회 결과'}</h2><span className="pill">{answer.generation==='llm'?'AI 초안':'문서·데이터 근거'}</span></div><p className="muted">{answer.notice}</p>{answer.warnings.map(w=><p className="warning" key={w}>{WARN[w]||w}</p>)}{answer.insufficient&&<p>임의의 결과를 만들지 않았습니다. 관련 문서·데이터를 등록하거나 담당자에게 확인해 주세요.</p>}{answer.statements.map((s,i)=><p className="quote" key={i}>{s.text}</p>)}<Metrics data={answer.metrics}/>{answer.records.length>0&&!answer.metrics&&<RecordTable records={answer.records}/>}<Evidence items={answer.evidence}/>{answer.draft&&<><h3>{answer.draft.kind} 미리보기</h3><pre>{answer.draft.text}</pre><button onClick={()=>run(async()=>{const r=await api('/reports',{...scope,kind:answer.draft.kind,question});setReport(r);setReports(await api('/reports'));setTab('reports');})}>초안으로 저장</button></>}<details><summary>처리 경로 · {answer.elapsed_ms} ms</summary><p>{answer.actions.join(' → ')}</p><p>{answer.routing} / {answer.retrieval}</p></details></section>}</>}
 {tab==='voyage'&&<><section className="panel"><div className="row"><h2>선박·기간별 기록</h2><button className="primary" onClick={()=>run(loadVoyage)}>조회 및 계산</button><select aria-label="비교 선박" defaultValue="" onChange={e=>{if(e.target.value)run(async()=>setCompare({name:vessels.find(v=>v.id===e.target.value)?.name,data:await api('/metrics',{...scope,vessel_id:e.target.value})}));}}><option value="">다른 선박과 비교</option>{vessels.filter(v=>v.id!==vessel).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></div><Metrics data={metric}/><RecordTable records={records} onEdit={editable?r=>{setEditRecord(r);setRecordJson(JSON.stringify({date:r.date,...r.data},null,2));}:null} onDelete={editable?r=>{if(confirm('이 운항 기록을 삭제할까요? 변경 이력에 원본이 남습니다.'))run(async()=>{await api('/records/'+r.id+'?version='+r.version,null,'DELETE');await loadVoyage();});}:null}/>{compare&&<><h3>비교: {compare.name}</h3><Metrics data={compare.data}/></>}</section>{editable&&<section className="panel"><h2>{editRecord?'운항 기록 수정':'Noon 데이터 등록'}</h2><p className="muted">연료 t, 거리 nm, 속력 kn, 위경도 °. 숫자에는 따옴표를 붙이지 마세요.</p><label>운항 데이터 JSON<textarea className="code" rows={15} value={recordJson} onChange={e=>setRecordJson(e.target.value)}/></label><div className="row"><button className="primary" onClick={()=>run(async()=>{const body={...JSON.parse(recordJson),vessel_id:vessel};await api(editRecord?'/records/'+editRecord.id+'?version='+editRecord.version:'/records',body,editRecord?'PUT':'POST');setEditRecord(null);await loadVoyage();setMessage('검증된 운항 기록을 저장했습니다.');})}>검증 후 저장</button>{editRecord&&<button onClick={()=>{setEditRecord(null);setRecordJson(JSON.stringify(sampleRecord,null,2));}}>수정 취소</button>}</div></section>}</>}
 {tab==='documents'&&<><section className="panel"><h2>등록 문서와 개정 이력</h2><p className="muted">현재 버전만 검색합니다. 구버전은 이전 보고서의 근거 확인용으로 보존합니다.</p><div className="doc-grid">{documents.map(d=><button className="doc-card" key={d.id} onClick={()=>run(async()=>setDoc(await api('/documents/'+d.id)))}><span className="pill">{d.status==='current'?'현재 버전':d.status==='withdrawn'?'폐기':'구버전'} · {d.metadata_json.restricted?'제한 문서':'일반 문서'}</span><h3>{d.title}</h3><p>v{d.version} · {d.metadata_json.issuer}</p><small>{d.metadata_json.applicability}</small></button>)}</div>{doc&&<div className="document-detail"><h3>{doc.title} · v{doc.version}</h3><p>{doc.status} · {doc.metadata_json.source_url}</p>{doc.chunks.map(c=><details key={c.id}><summary>{c.page?`p.${c.page}`:'페이지 미제공'} · {c.section}</summary><p className="preserve">{c.text}</p></details>)}{editable&&<div className="row"><button onClick={()=>setDocJson(JSON.stringify({logical_id:doc.logical_id,title:doc.title,version:doc.version+'-new',...doc.metadata_json,sections:doc.chunks.map(c=>({page:c.page,section:c.section,text:c.text}))},null,2))}>이 문서로 새 버전 작성</button><button className="danger" onClick={()=>{if(confirm('이 문서를 검색 대상에서 제외할까요? 기존 근거는 보존됩니다.'))run(async()=>{await api('/documents/'+doc.id,null,'DELETE');setDoc(null);await refresh();});}}>문서 폐기</button></div>}</div>}</section>{editable&&<section className="panel"><h2>문서 등록·새 버전 추가</h2><p className="muted">PDF는 실제 페이지를 보존합니다. 스캔본 OCR과 표 셀 구조 복원은 아직 지원하지 않습니다.</p><label>문서 정보 및 본문 JSON<textarea className="code" rows={14} value={docJson} onChange={e=>setDocJson(e.target.value)}/></label><div className="row"><button className="primary" onClick={()=>run(async()=>{const data=await api('/documents',JSON.parse(docJson));await refresh();setMessage('문서 등록 완료 · '+data.vector_status);})}>JSON 문서 등록</button><label className="upload">PDF로 본문 가져오기<input type="file" accept="application/pdf" onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{const metadata=JSON.parse(docJson);delete metadata.sections;const form=new FormData();form.append('metadata',JSON.stringify(metadata));form.append('file',file);const data=await api('/documents/pdf',form);await refresh();setMessage('PDF 등록 완료 · '+data.vector_status);});}}/></label></div></section>}</>}
 {tab==='reports'&&<><section className="panel"><div className="row"><div><h2>업무 보고서 초안</h2><p className="muted">선택한 선박·기간의 데이터와 Python 계산 결과로 작성합니다.</p></div><select aria-label="보고서 양식" value={kind} onChange={e=>setKind(e.target.value)}><option>Noon Report</option><option>MRV Report</option></select><button className="primary" onClick={()=>run(createDraft)}>초안 생성·저장</button></div><div className="report-list">{reports.map(r=><button key={r.id} onClick={()=>{if(report&&report.text&&!confirm('현재 편집 내용을 바꾸고 저장된 초안을 열까요?'))return;run(async()=>setReport(await api('/reports/'+r.id)));}}>{r.title}<span>v{r.version} · {r.created_at.slice(0,10)}</span></button>)}</div></section>{report&&<section className="panel"><label>제목<input value={report.title} onChange={e=>setReport({...report,title:e.target.value})}/></label><label>보고서 내용<textarea className="report-editor" rows={25} value={report.text} onChange={e=>setReport({...report,text:e.target.value})}/></label><div className="row"><button className="primary" onClick={()=>run(async()=>{setReport(await api('/reports/'+report.id,{title:report.title,text:report.text,version:report.version},'PUT'));setReports(await api('/reports'));setMessage('새 버전으로 저장했습니다.');})}>수정 내용 저장</button><button title="저장된 최신 버전을 내려받습니다. 편집 중이면 먼저 저장하세요." onClick={()=>{window.location.href='/api/reports/'+report.id+'/export?format=md';}}>Markdown 내려받기</button><button title="저장된 최신 버전을 내려받습니다. 편집 중이면 먼저 저장하세요." onClick={()=>{window.location.href='/api/reports/'+report.id+'/export?format=json';}}>근거·입력값 포함 JSON</button></div><details><summary>생성 당시 계산·근거 스냅샷</summary><pre>{JSON.stringify(report.snapshot,null,2)}</pre></details></section>}</>}
 {tab==='history'&&<section className="panel"><div className="row"><h2>질의·변경·도구 실행 이력</h2><button onClick={()=>run(async()=>setHistory(await api('/history')))}>새로고침</button></div><p className="muted">최근 100건. 일반 사용자는 본인 작업 요약을 조회합니다.</p>{history.map(h=><details key={h.id}><summary>{h.action}<span>{h.actor} · {new Date(h.created_at).toLocaleString('ko-KR')}</span></summary><p>{h.target}</p>{h.detail&&<pre>{JSON.stringify(h.detail,null,2)}</pre>}</details>)}</section>}
 {tab==='admin'&&user.role==='admin'&&<><section className="panel"><h2>사용자 계정</h2><p className="muted">관리자는 전체 자료, 담당자는 배정 선박의 등록·수정, 일반 사용자는 배정 선박의 조회와 본인 초안에 접근합니다.</p><ul>{accounts.map(a=><li key={a.id}><form className="row" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));run(async()=>{await api('/users/'+a.id,{role:f.role,vessels:f.vessels.split(',').map(s=>s.trim()).filter(Boolean),active:f.active==='true'},'PUT');setAccounts(await api('/users'));setMessage('권한을 변경하고 해당 사용자의 기존 세션을 종료했습니다.');});}}><b>{a.username}</b><select name="role" aria-label={a.username+' 역할'} defaultValue={a.role}><option value="crew">일반 사용자</option><option value="captain">선장·담당자</option><option value="admin">관리자</option></select><input name="vessels" aria-label={a.username+' 접근 선박'} defaultValue={a.vessels.join(', ')} placeholder="HAE-01, HAE-02"/><select name="active" aria-label={a.username+' 활성 상태'} defaultValue={String(a.active)}><option value="true">활성</option><option value="false">비활성</option></select><button disabled={a.id===user.id}>권한 저장</button></form></li>)}</ul><form className="admin-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=Object.fromEntries(new FormData(form));run(async()=>{await api('/users',{...f,vessels:f.vessels.split(',').map(s=>s.trim()).filter(Boolean)});setAccounts(await api('/users'));form.reset();setMessage('계정을 생성했습니다.');});}}><label>사용자 이름<input name="username" required maxLength={80}/></label><label>초기 비밀번호<input name="password" type="password" minLength={12} maxLength={256} required autoComplete="new-password"/></label><label>역할<select name="role"><option value="crew">일반 사용자</option><option value="captain">선장·담당자</option><option value="admin">관리자</option></select></label><label>접근 선박 ID (쉼표 구분)<input name="vessels" placeholder="HAE-01, HAE-02"/></label><button className="primary">계정 생성</button></form></section><section className="panel"><h2>선박 등록</h2><form className="admin-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=Object.fromEntries(new FormData(form));run(async()=>{await api('/vessels',{...f,dwt:Number(f.dwt),sample:false});await refresh();form.reset();setMessage('선박을 등록했습니다.');});}}><label>ID<input name="id" required pattern="[a-zA-Z0-9-]+"/></label><label>선박명<input name="name" required/></label><label>DWT (t)<input name="dwt" type="number" min="1" max="10000000" required/></label><label>선종<input name="ship_type" required/></label><button className="primary">선박 등록</button></form></section><section className="panel"><h2>운영 상태</h2><p>문서 검색: {health?.vectors?'BM25 + Chroma (색인 상태는 검색 결과에 표시)':'BM25 · 벡터 미설정'}</p><p>LLM: {health?.llm?(health.local_model?'로컬 모델 연결 설정됨':'외부 모델 연결 설정됨'):'미설정 · 원문과 Python 도구 사용'}</p><p className="muted">백업·빈 DB 복구는 README의 관리 명령을 사용하세요. 공식 규정 적합성 판정, OCR, 사용자 평가 KPI는 별도 검증 대상입니다.</p></section></>}
 </fieldset><footer>해,답 · 선원 업무 지원 / 근거·계산 결과는 담당자 검토 후 활용하세요.</footer></main></div></div>;
}

function RecordTable({records,onEdit,onDelete}){return <div className="table-wrap"><table><thead><tr><th>날짜 / 항차</th><th>상태 / 위치</th><th>속력</th><th>거리</th><th>연료</th>{onEdit&&<th>관리</th>}</tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.date}<small>{r.data.voyage}</small></td><td>{r.data.status}<small>{r.data.latitude}°, {r.data.longitude}°</small></td><td>{r.data.speed_kn} kn</td><td>{r.data.distance_nm} nm</td><td>{r.data.fuel_t} t</td>{onEdit&&<td><button onClick={()=>onEdit(r)}>수정</button> <button className="danger" onClick={()=>onDelete(r)}>삭제</button></td>}</tr>)}</tbody></table>{!records.length&&<p className="muted">조회된 운항 기록이 없습니다.</p>}</div>;}
