import {state,isAdmin} from './state.js';
import {esc,I,btn,badge,head,empty,dateText,n,options,notice,stat} from './helpers.js';
import {chartSVG} from './operations-view.js';
export const roleName={guest:'로그인 없이 사용 중',admin:'관리자 · 승인',operator:'업무 담당자',viewer:'열람 전용'};
export const statusName={draft:'작성 중',review:'검토 대기',approved:'승인 완료',pending:'승인 대기',rejected:'반려'};
export function authPage(){return `<main class="login-layout"><section class="login-brand"><div class="brandmark">${I('ship')}</div><h1>해답</h1><p>문서의 근거부터<br>오늘의 운항 기록까지.</p><small>선박 운항 업무지원</small></section><section class="login-card"><span class="eyebrow">HAEDAP WORKSPACE</span><h2>관리자 로그인</h2><p class="muted mb">관리 기능을 사용하려면 로그인해 주세요.<br>기본 기능은 로그인 없이 사용할 수 있습니다.</p><form id="authForm"><div class="field"><label for="auth-username">아이디</label><input id="auth-username" name="username" required maxlength="40" autocomplete="username"></div><div class="field"><label for="auth-password">비밀번호</label><input id="auth-password" name="password" type="password" required maxlength="128" autocomplete="current-password"></div><p class="inline-error mt" id="authError" role="alert">${esc(state.authError||state.connectionError)}</p><button type="submit" class="btn primary login-submit" ${state.connecting?'disabled':''}>${state.connecting?'연결 중…':'로그인'}</button></form>${btn('로그인 없이 돌아가기','cancelLogin','mt')}${state.connectionError?btn('서버 다시 연결','reconnect','mt'):''}</section></main>`;}
export function ciiText(cii,en=false){if(cii?.status==='available'&&Number.isFinite(cii.value))return `${en?'CII result':'CII 산출값'}: ${n(cii.value,3)} ${esc(cii.unit||'')} · ${en?'Rating':'등급'} ${esc(cii.rating||'미제공')} · ${esc(cii.year||'')} / ${esc(cii.method||'산식 확인 필요')}`;return en?'CII unavailable: verified annual coverage, vessel-specific method and adjustment criteria are required.':'CII 산출 불가: '+esc(cii?.reason||'산출 조건과 입력 데이터가 부족합니다.');}
export function operationAnswer(a){const s=a.operations;if(!s)return a.operationNotice?notice(esc(a.operationNotice)):'';const en=a.language==='en',c=a.compliance||{status:'unknown',label:'판단 불가',reason:'규정 근거 확인이 필요합니다.'};return `<section class="integrated-result mt"><div class="sectiontitle"><h3>${en?'Operations summary':'운항 데이터 요약'}</h3>${s.sample?badge(en?'Sample data':'가상 데이터','warn'):badge(en?'Saved records':'저장 기록','teal')}</div><p class="small muted">${esc(s.ship.name)} · ${s.from} ~ ${s.to} · ${s.count}${en?' records':'개 기록'}</p>${s.count?`<div class="grid3 mt">${stat(en?'Fuel':'연료',n(s.fuel),'t','')}${stat('CO₂',n(s.emission),'t','')}${stat(en?'Distance':'거리',n(s.distance),'nm','')}</div><div class="card pad mt"><h3>${en?'Daily CO₂ emissions':'일별 CO₂ 배출량'}</h3>${chartSVG([s.ship.id],'emission',s.rows,[s.ship],s.from,s.to)}<details><summary>${en?'View input records':'계산에 사용한 기록 보기'}</summary><div class="tablewrap"><table><thead><tr><th>${en?'Date':'일자'}</th><th>${en?'Fuel (t)':'연료 (t)'}</th><th>${en?'Factor':'배출계수'}</th><th>CO₂ (t)</th><th>nm</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td>${r.date}</td><td>${r.fuel}</td><td>${r.factor}</td><td>${n(r.fuel*r.factor,3)}</td><td>${r.distance}</td></tr>`).join('')}</tbody></table></div></details></div>`:notice(en?'No records for this period.':'해당 기간의 운항 기록이 없습니다.','warning')}<div class="card pad mt"><div class="sectiontitle"><h3>${en?'Rule comparison':'규정 기준 비교'}</h3>${badge(en?{met:'Entered criterion met',unmet:'Entered criterion not met',unknown:'Cannot determine'}[c.status]:c.label,c.status==='met'?'good':'warn')}</div>${c.rule?`<p class="small">${esc(c.rule.metric)}: ${n(c.actual,3)} / ${en?'Entered limit':'입력 기준'} ${n(c.limit,3)}<br>${esc(c.rule.quote)}</p>`:''}<p class="small muted">${esc(en?'A comparison against a user-verified criterion, not a complete regulatory compliance certification. Missing criteria or data produce no determination.':c.reason)}</p>${btn(en?'Review criterion':'적용 기준 확인','criterion','sm mt')}</div><p class="footnote mt">${ciiText(s.cii,en)}</p></section>`;}
export function adminPage(){if(!isAdmin())return empty('관리자 권한이 필요해요','사용자·승인·로그·백업은 관리자가 확인합니다.');const tab=state.adminTab;let content='';
 if(tab==='connection')content=`<div class="status-grid"><div class="card pad"><h2>작업공간 상태</h2>${[['서버','연결됨'],['문서',state.docs.filter(d=>d.active).length+'개'],['선박 / 운항 기록',state.ships.length+'척 / '+state.operationRecords.length+'건'],['보고서',state.reports.length+'개'],['AI 답변',state.health?.llmConfigured?'설정됨':'근거 문단 보기 사용']].map(([k,v])=>`<div class="status-line"><span>${k}</span><strong>${esc(v)}</strong></div>`).join('')}</div><div class="card pad"><h2>운영 안내</h2><p class="muted mt">문서와 운항 정보는 관리자만 등록·수정·삭제하며 저장 즉시 반영됩니다. 보고서는 승인 탭에서 검토합니다. 조회·질문·분석은 로그인 없이 사용할 수 있습니다.</p>${notice('텍스트 PDF 검색·기록 관리·계산·초안·백업은 로컬에서 동작합니다. 선택적 외부 AI 답변에는 인터넷이 필요합니다.')}<div class="mt">${btn('정보 새로고침','refreshAll','','refresh')}</div></div></div>`;
 if(tab==='users')content=`<div class="sectiontitle"><h3>사용자 ${state.users.length}명</h3>${btn('사용자 추가','newUser','primary','plus')}</div><div class="card tablewrap"><table><thead><tr><th>이름 / 아이디</th><th>권한</th><th>상태</th><th></th></tr></thead><tbody>${state.users.map(u=>`<tr><td>${esc(u.name)}<br><small>${esc(u.username)}</small></td><td>${roleName[u.role]}</td><td>${badge(u.active?'활성':'비활성',u.active?'good':'')}</td><td>${u.username==='admin'?'<span class="small muted">기본 관리자 · 고정</span>':btn('수정','editUser','sm','',`data-id="${u.id}"`)}</td></tr>`).join('')}</tbody></table></div>`;
 if(tab==='approvals')content=`<div class="sectiontitle"><h3>변경·보고서 검토</h3>${btn('새로고침','refreshAdmin','sm','refresh')}</div><div class="card">${state.changes.length?state.changes.map(c=>`<div class="docrow"><div class="docmain"><h3>${esc(changeLabel(c.kind))}</h3><p class="small muted">${esc(c.actor_name||'삭제된 사용자')} · ${dateText(c.at)}</p><p class="small">${esc(changeTarget(c))}</p>${badge(statusName[c.status],c.status==='pending'?'warn':'')}</div>${btn('검토 내용','reviewChange','sm','',`data-id="${c.id}"`)}</div>`).join(''):empty('검토할 요청이 없어요','업무 담당자의 변경 요청과 보고서 검토 요청이 표시됩니다.')}</div>`;
 if(tab==='logs'){const rows=state.logs.filter(l=>state.logFilter==='all'||l.category===state.logFilter);content=`<div class="controls"><select class="control" aria-label="로그 종류" data-field="logFilter">${options([['all','전체'],['query','질의'],['change','데이터 변경'],['error','오류'],['tool','계산'],['auth','로그인'],['report','보고서'],['backup','백업'],['users','사용자']],state.logFilter)}</select>${btn('새로고침','refreshAdmin','','refresh')}<span class="small muted">최근 500건</span></div><div class="card tablewrap"><table><thead><tr><th>시각</th><th>수행자</th><th>동작</th><th>대상</th><th></th></tr></thead><tbody>${rows.map(l=>`<tr><td>${dateText(l.at)}</td><td>${esc(l.actor)}</td><td>${esc(l.action)}</td><td class="truncate-cell">${esc(l.target)}</td><td>${btn('상세','logDetail','sm','',`data-id="${l.id}"`)}</td></tr>`).join('')||'<tr><td colspan="5">기록이 없습니다.</td></tr>'}</tbody></table></div>`;}
 if(tab==='backup')content=`<div class="sectiontitle"><div><h3>전체 데이터 백업</h3><p class="small muted mt">문서·원본 PDF·운항 기록·보고서·계정 및 권한·이력·시스템 설정 포함</p></div><div class="actions wrap">${btn('파일 가져오기','importBackup','','database')}${btn('백업 만들기','createBackup','primary','save')}</div></div>${notice('복구는 현재 데이터를 선택한 시점으로 되돌립니다. 복구 직전 자동 백업을 만들고, 모든 계정은 다시 로그인합니다.')}<div class="controls mt"><label for="auto-backup">자동 백업</label><select id="auto-backup" class="control" data-backup-setting="true">${options([['daily','하루 1회'],['off','사용 안 함']],state.autoBackup||'daily')}</select><span class="small muted">서버 실행 중 · UTC 날짜 기준 · 1분마다 확인</span></div><div class="card mt">${state.backups.length?state.backups.map(b=>`<div class="docrow"><div class="docmain"><h3>${esc(b.label)}</h3><p class="small muted">${dateText(b.createdAt)} · 형식 v${b.version}</p><p class="small">문서 ${b.counts.documents} · 운항 ${b.counts.operations} · 보고서 ${b.counts.reports}</p></div><div class="actions">${btn('파일 보관','downloadBackup','sm','download',`data-id="${b.id}"`)}${btn('복구','restoreBackup','sm','refresh',`data-id="${b.id}"`)}</div></div>`).join(''):empty('아직 백업이 없어요','중요한 데이터를 등록한 뒤 백업을 만들어 주세요.')}</div><p class="footnote mt">백업에는 계정 정보와 문서가 포함됩니다. 관리자만 내려받을 수 있습니다. 외부 AI 비밀키(.env)는 백업에서 제외되며 서버에서 별도로 보관합니다.</p>`;
 return head('관리','사용자와 변경 내역을 확인하고 데이터를 보관하세요.')+`<div class="admin-tabs">${[['connection','연결 상태'],['users','사용자·권한'],['approvals','승인'],['logs','시스템 로그'],['backup','백업·복구']].map(([id,l])=>btn(l,'adminTab',tab===id?'primary':'','',`data-id="${id}"`)).join('')}</div>${state.adminError?notice(esc(state.adminError),'warning'):''}${state.adminLoading?'<p role="status">불러오는 중…</p>':content}`;
}
export function changeLabel(kind){return {'document.save':'문서 등록·개정','document.delete':'문서 삭제','ship.save':'선박 등록·수정','operation.save':'운항 기록 등록·수정','operation.import':'운항 기록 일괄 등록','operation.delete':'운항 기록 삭제','report.approve':'보고서 확정 검토'}[kind]||kind;}
export function changeTarget(c){const p=c.payload;return p.document?.title||p.title||p.name||(p.rows?p.rows.length+'개 기록':p.date||p.id||'');}
