import {state,currentShip,records,metrics,canWrite,isAdmin} from './state.js';
import {esc,I,btn,badge,n,options,head,notice,empty,stat} from './helpers.js';
export const metricLabels={fuel:['연료 소비량','t'],emission:['CO₂ 배출량','t CO₂'],distance:['운항거리','nm'],speed:['속력','kn'],intensity:['단순 탄소집약도','gCO₂/(DWT·nm)']};
export function valueOf(r,key,ship){return key==='emission'?r.fuel*r.factor:key==='intensity'?(r.distance>0&&ship?.dwt>0?r.fuel*r.factor*1e6/(ship.dwt*r.distance):null):r[key];}
export function chartSVG(ids=[state.ship],metric=state.metric,source=state.operationRecords,vessels=state.ships,from=state.from,to=state.to){
 const lists=ids.map(id=>source.filter(r=>r.ship===id&&r.date>=from&&r.date<=to)),dates=[...new Set(lists.flat().map(r=>r.date))].sort();if(!dates.length)return empty('이 기간의 기록이 없어요','선박과 기간을 확인하거나 기록을 등록해 주세요.');
 const values=lists.flatMap((rs,i)=>rs.map(r=>valueOf(r,metric,vessels.find(s=>s.id===ids[i])))).filter(v=>v!==null),max=Math.max(1,...values)*1.1,W=900,H=220,left=70,right=30,top=15,bottom=35,x=i=>left+i*(W-left-right)/Math.max(1,dates.length-1),y=v=>H-bottom-v/max*(H-top-bottom);
 return `<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(metricLabels[metric][0])} 추이. 상세 값은 아래 표에서 확인할 수 있습니다.">${[0,.25,.5,.75,1].map(t=>`<line x1="${left}" y1="${y(t*max)}" x2="${W-right}" y2="${y(t*max)}" stroke="#e7eef1"/><text x="60" y="${y(t*max)+4}" text-anchor="end" font-size="11" fill="#7a8c98">${n(t*max,max>100?0:1)}</text>`).join('')}${dates.filter((_,i)=>i%Math.max(1,Math.ceil(dates.length/8))===0).map(d=>`<text x="${x(dates.indexOf(d))}" y="${H-7}" text-anchor="middle" fill="#7a8c98" font-size="11">${d.slice(5)}</text>`).join('')}${lists.map((list,ix)=>{const color=['#167d83','#8e9fb7','#c89962'][ix%3],ship=vessels.find(s=>s.id===ids[ix]),valid=list.filter(r=>valueOf(r,metric,ship)!==null);return `<polyline fill="none" stroke="${color}" stroke-width="2.7" points="${valid.map(r=>[x(dates.indexOf(r.date)),y(valueOf(r,metric,ship))].join(',')).join(' ')}"/>${valid.map(r=>`<circle cx="${x(dates.indexOf(r.date))}" cy="${y(valueOf(r,metric,ship))}" r="3" fill="${color}"><title>${esc(ship?.name)} ${r.date}: ${n(valueOf(r,metric,ship),3)}</title></circle>`).join('')}`;}).join('')}</svg>`;
}
export function operationTable(rows,editable=false){return `<div class="tablewrap"><table><thead><tr><th>선박 / 일자</th><th>연료 (t)</th><th>CO₂ (t)</th><th>거리 (nm)</th><th>속력 (kn)</th><th>확인</th>${editable?'<th>관리</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(state.ships.find(s=>s.id===r.ship)?.name||r.ship)}<br><small>${r.date}</small></td><td>${n(r.fuel)}</td><td>${n(r.fuel*r.factor)}</td><td>${n(r.distance)}</td><td>${n(r.speed)}</td><td>${badge(r.sample?'가상 예시':r.note?'점검 기록':'등록 기록',r.sample?'warn':'')}<button class="tabletitle" data-action="recordDetail" data-id="${esc(r.id)}">상세</button></td>${editable?`<td><div class="actions">${btn('수정','editRecord','sm','',`data-id="${esc(r.id)}"`)}${btn('삭제','deleteRecord','ghost sm','',`data-id="${esc(r.id)}"`)}</div></td>`:''}</tr>`).join('')}</tbody></table></div>`;}
export function contextControls(compact=false){return `<div class="controls ${compact?'context-controls':''}"><div class="field"><label for="ship">대상 선박</label><select id="ship" data-field="ship">${options([['','선박 선택'],...state.ships.map(s=>[s.id,s.name+(s.sample?' · 예시':'')])],state.ship)}</select></div><div class="field"><label for="from">시작일</label><input id="from" type="date" data-field="from" value="${state.from}"></div><div class="field"><label for="to">종료일</label><input id="to" type="date" data-field="to" value="${state.to}"></div></div>`;}
function overview(){const m=metrics(),s=currentShip(),rows=records(),last=rows.at(-1);return `<div class="grid4">${stat('연료 소비량',n(m.fuel),'t',`${m.count}개 기록 합계`)}${stat('CO₂ 배출량',n(m.co2),'t','기록별 배출계수 적용')}${stat('운항거리',n(m.distance),'nm','선택 기간 합계','ship')}${stat('점검 기록',m.anomalies,'건','점검 사유가 입력된 기록','alert')}</div><div class="card ship-strip"><div><h3>${esc(s.name)} ${s.sample?badge('가상 예시','warn'):''}</h3><span class="muted small">${esc(s.type||'')} · DWT ${n(s.dwt,0)} t</span></div><div class="small muted">최근 기록 ${last?.date||'없음'}<br>위치 ${esc(last?.position||'미입력')} · 속력 ${last?n(last.speed)+' kn':'—'}</div>${isAdmin()?btn('선박 정보','editShip','sm','',`data-id="${esc(s.id)}"`):''}</div>${analysisChart([state.ship])}<div class="sectiontitle mt"><h3>운항 기록 ${rows.length}건</h3>${btn('CSV 내보내기','exportRecords','ghost sm','download')}</div><div class="card">${rows.length?operationTable(rows,isAdmin()):empty('등록된 기록이 없어요','선택한 선박·기간의 기록을 등록해 주세요.')}</div>${timeTool()}`;}
function analysisChart(ids){return `<div class="card pad"><div class="sectiontitle"><h3>${esc(metricLabels[state.metric][0])} 추이</h3><select class="control" aria-label="표시 지표" data-field="metric">${options(Object.entries(metricLabels).map(([k,v])=>[k,v[0]]),state.metric)}</select></div>${chartSVG(ids)}<p class="small muted">단위: ${metricLabels[state.metric][1]} · CII 등급을 의미하지 않습니다.</p></div>`;}
function analysis(){const ids=state.compare.length?state.compare:[state.ship];return `<div class="compare-controls mb">${state.ships.map(s=>`<label class="checkline"><input type="checkbox" data-compare="${esc(s.id)}" ${ids.includes(s.id)?'checked':''}>${esc(s.name)}</label>`).join('')}</div>${analysisChart(ids)}<div class="legend mt">${ids.map((id,i)=>`<span style="--legend-color:${['#167d83','#8e9fb7','#c89962'][i%3]}">${esc(state.ships.find(s=>s.id===id)?.name)}</span>`).join('')}</div><div class="card mt">${operationTable(ids.flatMap(id=>records(id)))}</div>`;}
function calculation(){const c=state.calc,v=state.calcInputs;return `<div class="grid2"><form id="calcForm" class="card pad"><div class="sectiontitle"><h3>계산 입력값</h3>${badge('서버 계산','teal')}</div>${btn('선택 기록에서 가져오기','useSampleInputs','sm mb','database')}<div class="grid2 mb">${[['fuel','연료 소비량 (t)',0,1e7],['factor','배출계수 (t CO₂/t)',.000001,10],['dwt','재화중량 (DWT, t)',.000001,1e7],['distance','운항거리 (nm)',.000001,1e7]].map(([id,l,min,max])=>`<div class="field"><label for="${id}">${l}</label><input id="${id}" name="${id}" data-calc="${id}" type="number" min="${min}" max="${max}" step="any" value="${esc(v[id])}" required></div>`).join('')}</div><div class="inline-error mb" role="alert">${esc(state.calcError)}</div><button class="btn primary" ${state.calcBusy?'disabled':''}>${state.calcBusy?'계산 중…':'지표 계산'}</button></form><div><div class="calculation-result" aria-live="polite"><h3>계산 결과</h3>${c?`<div class="mt">CO₂ 배출량</div><div class="stat-value">${n(c.emission,3)} <small>t CO₂</small></div><div class="divider"></div><div>단순 탄소집약도</div><div class="stat-value">${n(c.intensity,3)} <small>gCO₂/(DWT·nm)</small></div><p class="formula">${esc(c.formula)}<br>계산 버전: ${esc(c.version)}</p>`:'<p class="mt">입력값을 확인하고 계산을 실행하세요.</p>'}</div><div class="card pad mt"><h3>CII ${badge('산출 불가','warn')}</h3><p class="small muted mt">공식 CII 산식·선종별 용량 기준·보정 및 제외 조건·적용 연도 검증이 필요합니다. 위 단순 집약도를 CII 등급으로 사용하지 마세요.</p></div>${c&&canWrite()?btn('계산 결과를 보고서에 담기','calcReport','mt','edit'):''}</div></div>`;}
function timeTool(){const t=state.timeInputs,r=state.timeResult;return `<details class="card pad time-tool"><summary>항해 시각 계산</summary><form id="timeForm"><div class="grid2">${[['start','시작 UTC','datetime-local'],['end','종료 UTC','datetime-local'],['before','시작 오프셋 (분)','number'],['after','종료 오프셋 (분)','number']].map(([id,l,type])=>`<div class="field"><label for="time-${id}">${l}</label><input id="time-${id}" data-time="${id}" type="${type}" value="${t[id]}" required></div>`).join('')}</div><p class="inline-error" role="alert">${esc(state.timeError)}</p><button class="btn" ${state.timeBusy?'disabled':''}>시간 계산</button></form>${r?`<p class="mt">실제 경과 ${n(r.elapsedHours)}시간 · 선내 시계 차이 ${n(r.clockHours)}시간</p>`:''}</details>`;}
export function operationsPage(){return head('운항 정보','기록을 관리하고, 변화를 비교하고, 지표를 계산하세요.',isAdmin()?btn('선박 등록','newShip','','ship')+btn('CSV 불러오기','importOperations','','database')+btn('기록 등록','newRecord','primary','plus'):'')+contextControls()+`<div class="tabs">${[['overview','현황'],['analysis','분석'],['calculation','지표 계산']].map(([id,l])=>`<button class="tab ${state.tab===id?'active':''}" data-tab="${id}">${l}</button>`).join('')}</div>`+(state.tab!=='calculation'&&!state.ships.length?empty('첫 선박을 등록해 주세요','새로 등록한 기록은 SQLite에 저장됩니다.',isAdmin()?btn('선박 등록','newShip','primary')+(isAdmin()?btn('가상 예시로 둘러보기','seedExample','mt'):''):'관리자에게 선박 등록을 요청해 주세요.'):{overview,analysis,calculation}[state.tab]());}
